//#########################################################################
//generated by PostgreSQLMetal on 2008-Feb-04 - extracted from server localhost.
//#########################################################################

using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Text;
using System.Linq;
//using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Reflection;
using DbLinq.Linq;
using DbLinq.Linq.Mapping;
using DbLinq.PostgreSql;

namespace nwind
{
    
	/// <summary>
	/// This class represents PostgreSQL database Northwind.
	/// </summary>
	public partial class Northwind : DataContext
	{
		public Northwind(string connStr) : base(new Npgsql.NpgsqlConnection( connStr), new PgsqlVendor())
		{
		}
		public Northwind(System.Data.IDbConnection connection) : base(connection, new PgsqlVendor())
		{
		}
	
		//these fields represent tables in database and are
		//ordered - parent tables first, child tables next. Do not change the order.
		public Table<Category> Categories { get { return base.GetTable<Category>("Categories"); } }
		public Table<Employee> Employees { get { return base.GetTable<Employee>("Employees"); } }
		public Table<Alltype> Alltypes { get { return base.GetTable<Alltype>("Alltypes"); } }
		public Table<Customer> Customers { get { return base.GetTable<Customer>("Customers"); } }
		public Table<Shipper> Shippers { get { return base.GetTable<Shipper>("Shippers"); } }
		public Table<Region> Regions { get { return base.GetTable<Region>("Regions"); } }
		public Table<Supplier> Suppliers { get { return base.GetTable<Supplier>("Suppliers"); } }
		public Table<Product> Products { get { return base.GetTable<Product>("Products"); } }
		public Table<OrderDetail> OrderDetails { get { return base.GetTable<OrderDetail>("OrderDetails"); } }
		public Table<Order> Orders { get { return base.GetTable<Order>("Orders"); } }
		public Table<Territory> Territories { get { return base.GetTable<Territory>("Territories"); } }
		public Table<Employeeterritory> Employeeterritories { get { return base.GetTable<Employeeterritory>("Employeeterritories"); } }
	
		#region stored procs
	
		
		[FunctionEx(Name = "hello0", ProcedureOrFunction = "")]	
		public string Hello0()	
		{	
			System.Data.Linq.IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));	
			return (string)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "hello1", ProcedureOrFunction = "")]	
		public string Hello1([Parameter(Name = "name", DbType = "text")] string name)	
		{	
			System.Data.Linq.IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);	
			return (string)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "hello2", ProcedureOrFunction = "")]	
		public string hello2([Parameter(Name = "name", DbType = "text")] string name
				,[Parameter(Name = "unused", DbType = "text")] string unused)	
		{	
			System.Data.Linq.IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, unused);	
			return (string)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "getordercount", ProcedureOrFunction = "")]	
		public int GetOrderCount([Parameter(Name = "custid", DbType = "character varying")] string custid)	
		{	
			System.Data.Linq.IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), custid);	
			return (int)result.ReturnValue;	
		}	
		
	
	#endregion
	}
	
	
	
	[Table(Name = "public.categories")]
	public partial class Category : IModified
	{
		[DbLinq.Linq.Mapping.AutoGenId] 
		protected int _categoryid;
		protected string _categoryname;
		protected string _description;
		protected byte[] _picture;
	
		
		public Category()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_categoryid", Name = "categoryid", DbType = "integer(32,0)", IsPrimaryKey = true, IsDbGenerated = true, Expression = "nextval('categories_categoryid_seq')")]
		[DebuggerNonUserCode]
		public int CategoryID
		{
		    get { return _categoryid; }
		    set { _categoryid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_categoryname", Name = "categoryname", DbType = "character varying(15)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CategoryName
		{
		    get { return _categoryname; }
		    set { _categoryname = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_description", Name = "description", DbType = "text", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Description
		{
		    get { return _description; }
		    set { _description = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_picture", Name = "picture", DbType = "oid", CanBeNull = true)]
		[DebuggerNonUserCode]
		public byte[] Picture
		{
		    get { return _picture; }
		    set { _picture = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _categoryid.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Category o2 = obj as Category;
			if(o2==null)
				return false;
			return _categoryid == o2._categoryid;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "categoryid", Name = "fk_prod_catg")]
		public EntityMSet<Product> Products
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.employees")]
	public partial class Employee : IModified
	{
		[DbLinq.Linq.Mapping.AutoGenId] 
		protected int _employeeid;
		protected string _lastname;
		protected string _firstname;
		protected string _title;
		protected DateTime? _birthdate;
		protected DateTime? _hiredate;
		protected string _address;
		protected string _city;
		protected string _region;
		protected string _postalcode;
		protected string _country;
		protected string _homephone;
		protected byte[] _photo;
		protected string _notes;
		protected int? _reportsto;
	
		
		public Employee()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_employeeid", Name = "employeeid", DbType = "integer(32,0)", IsPrimaryKey = true, IsDbGenerated = true, Expression = "nextval('employees_employeeid_seq')")]
		[DebuggerNonUserCode]
		public int EmployeeID
		{
		    get { return _employeeid; }
		    set { _employeeid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_lastname", Name = "lastname", DbType = "character varying(20)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string LastName
		{
		    get { return _lastname; }
		    set { _lastname = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_firstname", Name = "firstname", DbType = "character varying(10)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string FirstName
		{
		    get { return _firstname; }
		    set { _firstname = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_title", Name = "title", DbType = "character varying(30)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Title
		{
		    get { return _title; }
		    set { _title = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_birthdate", Name = "birthdate", DbType = "date", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? Birthdate
		{
		    get { return _birthdate; }
		    set { _birthdate = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_hiredate", Name = "hiredate", DbType = "timestamp without time zone", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? HireDate
		{
		    get { return _hiredate; }
		    set { _hiredate = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_address", Name = "address", DbType = "character varying(60)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Address
		{
		    get { return _address; }
		    set { _address = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_city", Name = "city", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string City
		{
		    get { return _city; }
		    set { _city = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_region", Name = "region", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Region
		{
		    get { return _region; }
		    set { _region = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_postalcode", Name = "postalcode", DbType = "character varying(10)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string PostalCode
		{
		    get { return _postalcode; }
		    set { _postalcode = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_country", Name = "country", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Country
		{
		    get { return _country; }
		    set { _country = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_homephone", Name = "homephone", DbType = "character varying(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Homephone
		{
		    get { return _homephone; }
		    set { _homephone = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_photo", Name = "photo", DbType = "oid", CanBeNull = true)]
		[DebuggerNonUserCode]
		public byte[] Photo
		{
		    get { return _photo; }
		    set { _photo = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_notes", Name = "notes", DbType = "text", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Notes
		{
		    get { return _notes; }
		    set { _notes = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_reportsto", Name = "reportsto", DbType = "integer(32,0)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? ReportsTo
		{
		    get { return _reportsto; }
		    set { _reportsto = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _employeeid.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Employee o2 = obj as Employee;
			if(o2==null)
				return false;
			return _employeeid == o2._employeeid;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "reportsto", Name = "fk_emp_reportstoemp")]
		public EntityMSet<Employee> Employees
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		
		[Association(Storage = "null", OtherKey = "employeeid", Name = "employeeterritories_employeeid_fkey")]
		public EntityMSet<Employeeterritory> EmployeeTerritories
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		
		[Association(Storage = "null", OtherKey = "employeeid", Name = "fk_order_product")]
		public EntityMSet<Order> Orders
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Employee> _reportstoEmployee;    
		
		[Association(Storage="_reportstoEmployee", ThisKey="reportsto", Name="fk_emp_reportstoemp")]
		[DebuggerNonUserCode]
		public Employee reportstoEmployee {
			get { return this._reportstoEmployee.Entity; }
			set { this._reportstoEmployee.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.alltypes")]
	public partial class Alltype : IModified
	{
		[DbLinq.Linq.Mapping.AutoGenId] 
		protected int _int;
		protected int? _intn;
		protected double _double;
		protected double? _doublen;
		protected decimal _decimal;
		protected decimal? _decimaln;
		protected DateTime _datetime;
		protected DateTime? _datetimen;
	
		
		public Alltype()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_int", Name = "int", DbType = "integer(32,0)", IsPrimaryKey = true, IsDbGenerated = true, Expression = "nextval('alltypes_int_seq')")]
		[DebuggerNonUserCode]
		public int Int
		{
		    get { return _int; }
		    set { _int = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_intn", Name = "intn", DbType = "integer(32,0)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? Intn
		{
		    get { return _intn; }
		    set { _intn = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_double", Name = "double", DbType = "double precision", CanBeNull = false)]
		[DebuggerNonUserCode]
		public double Double
		{
		    get { return _double; }
		    set { _double = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_doublen", Name = "doublen", DbType = "double precision", CanBeNull = true)]
		[DebuggerNonUserCode]
		public double? Doublen
		{
		    get { return _doublen; }
		    set { _doublen = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_decimal", Name = "decimal", DbType = "numeric", CanBeNull = false)]
		[DebuggerNonUserCode]
		public decimal Decimal
		{
		    get { return _decimal; }
		    set { _decimal = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_decimaln", Name = "decimaln", DbType = "numeric", CanBeNull = true)]
		[DebuggerNonUserCode]
		public decimal? Decimaln
		{
		    get { return _decimaln; }
		    set { _decimaln = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_datetime", Name = "datetime", DbType = "timestamp without time zone", CanBeNull = false)]
		[DebuggerNonUserCode]
		public DateTime Datetime
		{
		    get { return _datetime; }
		    set { _datetime = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_datetimen", Name = "datetimen", DbType = "timestamp without time zone", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? Datetimen
		{
		    get { return _datetimen; }
		    set { _datetimen = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _int.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Alltype o2 = obj as Alltype;
			if(o2==null)
				return false;
			return _int == o2._int;
		}
		#endregion
	
		#region childtables
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.customers")]
	public partial class Customer //: IModified
	{
		
		protected string _customerid;
		protected string _companyname;
		protected string _contactname;
		protected string _contacttitle;
		protected string _address;
		protected string _city;
		protected string _region;
		protected string _postalcode;
		protected string _country;
		protected string _phone;
		protected string _fax;
	
		
		public Customer()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_customerid", Name = "customerid", DbType = "character varying(5)", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public string CustomerID
		{
		    get { return _customerid; }
		    set { _customerid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_companyname", Name = "companyname", DbType = "character varying(40)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CompanyName
		{
		    get { return _companyname; }
		    set { _companyname = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_contactname", Name = "contactname", DbType = "character varying(30)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string ContactName
		{
		    get { return _contactname; }
		    set { _contactname = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_contacttitle", Name = "contacttitle", DbType = "character varying(30)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Contacttitle
		{
		    get { return _contacttitle; }
		    set { _contacttitle = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_address", Name = "address", DbType = "character varying(60)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Address
		{
		    get { return _address; }
		    set { _address = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_city", Name = "city", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string City
		{
		    get { return _city; }
		    set { _city = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_region", Name = "region", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Region
		{
		    get { return _region; }
		    set { _region = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_postalcode", Name = "postalcode", DbType = "character varying(10)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string PostalCode
		{
		    get { return _postalcode; }
		    set { _postalcode = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_country", Name = "country", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Country
		{
		    get { return _country; }
		    set { _country = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_phone", Name = "phone", DbType = "character varying(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Phone
		{
		    get { return _phone; }
		    set { _phone = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_fax", Name = "fax", DbType = "character varying(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Fax
		{
		    get { return _fax; }
		    set { _fax = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return (_customerid == null ? 0 : _customerid.GetHashCode());
		}
		public override bool Equals(object obj)
		{
			Customer o2 = obj as Customer;
			if(o2==null)
				return false;
			return object.Equals(_customerid, o2._customerid);
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "customerid", Name = "fk_order_customer")]
		public EntityMSet<Order> Orders
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.shippers")]
	public partial class Shipper : IModified
	{
		[DbLinq.Linq.Mapping.AutoGenId] 
		protected int _shipperid;
		protected string _companyname;
		protected string _phone;
	
		
		public Shipper()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_shipperid", Name = "shipperid", DbType = "integer(32,0)", IsPrimaryKey = true, IsDbGenerated = true, Expression = "nextval('shippers_shipperid_seq')")]
		[DebuggerNonUserCode]
		public int ShipperID
		{
		    get { return _shipperid; }
		    set { _shipperid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_companyname", Name = "companyname", DbType = "character varying(40)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CompanyName
		{
		    get { return _companyname; }
		    set { _companyname = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_phone", Name = "phone", DbType = "character varying(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Phone
		{
		    get { return _phone; }
		    set { _phone = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _shipperid.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Shipper o2 = obj as Shipper;
			if(o2==null)
				return false;
			return _shipperid == o2._shipperid;
		}
		#endregion
	
		#region childtables
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.region")]
	public partial class Region : IModified
	{
		[DbLinq.Linq.Mapping.AutoGenId] 
		protected int _regionid;
		protected string _regiondescription;
	
		
		public Region()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_regionid", Name = "regionid", DbType = "integer(32,0)", IsPrimaryKey = true, IsDbGenerated = true, Expression = "nextval('region_regionid_seq')")]
		[DebuggerNonUserCode]
		public int RegionID
		{
		    get { return _regionid; }
		    set { _regionid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_regiondescription", Name = "regiondescription", DbType = "character varying(50)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string RegionDescription
		{
		    get { return _regiondescription; }
		    set { _regiondescription = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _regionid.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Region o2 = obj as Region;
			if(o2==null)
				return false;
			return _regionid == o2._regionid;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "regionid", Name = "fk_terr_region")]
		public EntityMSet<Territory> Territories
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.suppliers")]
	public partial class Supplier : IModified
	{
		[DbLinq.Linq.Mapping.AutoGenId] 
		protected int _supplierid;
		protected string _companyname;
		protected string _contactname;
		protected string _contacttitle;
		protected string _address;
		protected string _city;
		protected string _region;
		protected string _postalcode;
		protected string _country;
		protected string _phone;
		protected string _fax;
	
		
		public Supplier()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_supplierid", Name = "supplierid", DbType = "integer(32,0)", IsPrimaryKey = true, IsDbGenerated = true, Expression = "nextval('suppliers_supplierid_seq')")]
		[DebuggerNonUserCode]
		public int SupplierID
		{
		    get { return _supplierid; }
		    set { _supplierid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_companyname", Name = "companyname", DbType = "character varying(40)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CompanyName
		{
		    get { return _companyname; }
		    set { _companyname = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_contactname", Name = "contactname", DbType = "character varying(30)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ContactName
		{
		    get { return _contactname; }
		    set { _contactname = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_contacttitle", Name = "contacttitle", DbType = "character varying(30)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Contacttitle
		{
		    get { return _contacttitle; }
		    set { _contacttitle = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_address", Name = "address", DbType = "character varying(60)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Address
		{
		    get { return _address; }
		    set { _address = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_city", Name = "city", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string City
		{
		    get { return _city; }
		    set { _city = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_region", Name = "region", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Region
		{
		    get { return _region; }
		    set { _region = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_postalcode", Name = "postalcode", DbType = "character varying(10)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string PostalCode
		{
		    get { return _postalcode; }
		    set { _postalcode = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_country", Name = "country", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Country
		{
		    get { return _country; }
		    set { _country = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_phone", Name = "phone", DbType = "character varying(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Phone
		{
		    get { return _phone; }
		    set { _phone = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_fax", Name = "fax", DbType = "character varying(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Fax
		{
		    get { return _fax; }
		    set { _fax = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _supplierid.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Supplier o2 = obj as Supplier;
			if(o2==null)
				return false;
			return _supplierid == o2._supplierid;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "supplierid", Name = "fk_prod_supp")]
		public EntityMSet<Product> Products
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.products")]
	public partial class Product : IModified
	{
		[DbLinq.Linq.Mapping.AutoGenId] 
		protected int _productid;
		protected string _productname;
		protected int? _supplierid;
		protected int? _categoryid;
		protected string _quantityperunit;
		protected decimal? _unitprice;
		protected short? _unitsinstock;
		protected short? _unitsonorder;
		protected short? _reorderlevel;
		protected bool _discontinued;
	
		
		public Product()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_productid", Name = "productid", DbType = "integer(32,0)", IsPrimaryKey = true, IsDbGenerated = true, Expression = "nextval('products_productid_seq')")]
		[DebuggerNonUserCode]
		public int ProductID
		{
		    get { return _productid; }
		    set { _productid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_productname", Name = "productname", DbType = "character varying(40)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string ProductName
		{
		    get { return _productname; }
		    set { _productname = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_supplierid", Name = "supplierid", DbType = "integer(32,0)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? SupplierID
		{
		    get { return _supplierid; }
		    set { _supplierid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_categoryid", Name = "categoryid", DbType = "integer(32,0)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? CategoryID
		{
		    get { return _categoryid; }
		    set { _categoryid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_quantityperunit", Name = "quantityperunit", DbType = "character varying(20)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string QuantityPerUnit
		{
		    get { return _quantityperunit; }
		    set { _quantityperunit = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_unitprice", Name = "unitprice", DbType = "numeric", CanBeNull = true)]
		[DebuggerNonUserCode]
		public decimal? UnitPrice
		{
		    get { return _unitprice; }
		    set { _unitprice = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_unitsinstock", Name = "unitsinstock", DbType = "smallint(16,0)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? UnitsInStock
		{
		    get { return _unitsinstock; }
		    set { _unitsinstock = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_unitsonorder", Name = "unitsonorder", DbType = "smallint(16,0)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? UnitsOnOrder
		{
		    get { return _unitsonorder; }
		    set { _unitsonorder = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_reorderlevel", Name = "reorderlevel", DbType = "smallint(16,0)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? Reorderlevel
		{
		    get { return _reorderlevel; }
		    set { _reorderlevel = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_discontinued", Name = "discontinued", DbType = "bit(1)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public bool Discontinued
		{
		    get { return _discontinued; }
		    set { _discontinued = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _productid.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Product o2 = obj as Product;
			if(o2==null)
				return false;
			return _productid == o2._productid;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "productid", Name = "orderdetails_productid_fkey")]
		public EntityMSet<OrderDetail> OrderDetails
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Category> _Category;    
		
		[Association(Storage="_Category", ThisKey="categoryid", Name="fk_prod_catg")]
		[DebuggerNonUserCode]
		public Category Category {
			get { return this._Category.Entity; }
			set { this._Category.Entity = value; }
		}
		
		private System.Data.Linq.EntityRef<Supplier> _Supplier;    
		
		[Association(Storage="_Supplier", ThisKey="supplierid", Name="fk_prod_supp")]
		[DebuggerNonUserCode]
		public Supplier Supplier {
			get { return this._Supplier.Entity; }
			set { this._Supplier.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.orderdetails")]
	public partial class OrderDetail : IModified
	{
		
		protected int _orderid;
		protected int _productid;
		protected decimal? _unitprice;
		protected double? _discount;
	
		
		public OrderDetail()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_orderid", Name = "orderid", DbType = "integer(32,0)", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public int OrderID
		{
		    get { return _orderid; }
		    set { _orderid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_productid", Name = "productid", DbType = "integer(32,0)", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public int ProductID
		{
		    get { return _productid; }
		    set { _productid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_unitprice", Name = "unitprice", DbType = "numeric", CanBeNull = true)]
		[DebuggerNonUserCode]
		public decimal? UnitPrice
		{
		    get { return _unitprice; }
		    set { _unitprice = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_discount", Name = "discount", DbType = "double precision", CanBeNull = true)]
		[DebuggerNonUserCode]
		public double? Discount
		{
		    get { return _discount; }
		    set { _discount = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _orderid.GetHashCode() ^ _productid.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			OrderDetail o2 = obj as OrderDetail;
			if(o2==null)
				return false;
			return _orderid == o2._orderid && _productid == o2._productid;
		}
		#endregion
	
		#region childtables
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Order> _Order;    
		
		[Association(Storage="_Order", ThisKey="orderid", Name="orderdetails_orderid_fkey")]
		[DebuggerNonUserCode]
		public Order Order {
			get { return this._Order.Entity; }
			set { this._Order.Entity = value; }
		}
		
		private System.Data.Linq.EntityRef<Product> _Product;    
		
		[Association(Storage="_Product", ThisKey="productid", Name="orderdetails_productid_fkey")]
		[DebuggerNonUserCode]
		public Product Product {
			get { return this._Product.Entity; }
			set { this._Product.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.orders")]
	public partial class Order : IModified
	{
		[DbLinq.Linq.Mapping.AutoGenId] 
		protected int _orderid;
		protected string _customerid;
		protected int? _employeeid;
		protected DateTime? _orderdate;
		protected DateTime? _requireddate;
		protected DateTime? _shippeddate;
		protected int? _shipvia;
		protected decimal? _freight;
		protected string _shipname;
		protected string _shipaddress;
		protected string _shipcity;
		protected string _shipregion;
		protected string _shippostalcode;
		protected string _shipcountry;
	
		
		public Order()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_orderid", Name = "orderid", DbType = "integer(32,0)", IsPrimaryKey = true, IsDbGenerated = true, Expression = "nextval('orders_orderid_seq')")]
		[DebuggerNonUserCode]
		public int OrderID
		{
		    get { return _orderid; }
		    set { _orderid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_customerid", Name = "customerid", DbType = "character varying(5)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CustomerID
		{
		    get { return _customerid; }
		    set { _customerid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_employeeid", Name = "employeeid", DbType = "integer(32,0)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? EmployeeID
		{
		    get { return _employeeid; }
		    set { _employeeid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_orderdate", Name = "orderdate", DbType = "timestamp without time zone", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? OrderDate
		{
		    get { return _orderdate; }
		    set { _orderdate = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_requireddate", Name = "requireddate", DbType = "timestamp without time zone", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? Requireddate
		{
		    get { return _requireddate; }
		    set { _requireddate = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_shippeddate", Name = "shippeddate", DbType = "timestamp without time zone", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? Shippeddate
		{
		    get { return _shippeddate; }
		    set { _shippeddate = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_shipvia", Name = "shipvia", DbType = "integer(32,0)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? Shipvia
		{
		    get { return _shipvia; }
		    set { _shipvia = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_freight", Name = "freight", DbType = "numeric", CanBeNull = true)]
		[DebuggerNonUserCode]
		public decimal? Freight
		{
		    get { return _freight; }
		    set { _freight = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_shipname", Name = "shipname", DbType = "character varying(40)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Shipname
		{
		    get { return _shipname; }
		    set { _shipname = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_shipaddress", Name = "shipaddress", DbType = "character varying(60)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Shipaddress
		{
		    get { return _shipaddress; }
		    set { _shipaddress = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_shipcity", Name = "shipcity", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ShipCity
		{
		    get { return _shipcity; }
		    set { _shipcity = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_shipregion", Name = "shipregion", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ShipRegion
		{
		    get { return _shipregion; }
		    set { _shipregion = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_shippostalcode", Name = "shippostalcode", DbType = "character varying(10)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Shippostalcode
		{
		    get { return _shippostalcode; }
		    set { _shippostalcode = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_shipcountry", Name = "shipcountry", DbType = "character varying(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Shipcountry
		{
		    get { return _shipcountry; }
		    set { _shipcountry = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _orderid.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Order o2 = obj as Order;
			if(o2==null)
				return false;
			return _orderid == o2._orderid;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "orderid", Name = "orderdetails_orderid_fkey")]
		public EntityMSet<OrderDetail> OrderDetails
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Customer> _Customer;    
		
		[Association(Storage="_Customer", ThisKey="customerid", Name="fk_order_customer")]
		[DebuggerNonUserCode]
		public Customer Customer {
			get { return this._Customer.Entity; }
			set { this._Customer.Entity = value; }
		}
		
		private System.Data.Linq.EntityRef<Employee> _Employee;    
		
		[Association(Storage="_Employee", ThisKey="employeeid", Name="fk_order_product")]
		[DebuggerNonUserCode]
		public Employee Employee {
			get { return this._Employee.Entity; }
			set { this._Employee.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.territories")]
	public partial class Territory : IModified
	{
		
		protected string _territoryid;
		protected string _territorydescription;
		protected int _regionid;
	
		
		public Territory()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_territoryid", Name = "territoryid", DbType = "character varying(20)", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public string TerritoryID
		{
		    get { return _territoryid; }
		    set { _territoryid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_territorydescription", Name = "territorydescription", DbType = "character varying(50)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string TerritoryDescription
		{
		    get { return _territorydescription; }
		    set { _territorydescription = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_regionid", Name = "regionid", DbType = "integer(32,0)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public int RegionID
		{
		    get { return _regionid; }
		    set { _regionid = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return (_territoryid == null ? 0 : _territoryid.GetHashCode());
		}
		public override bool Equals(object obj)
		{
			Territory o2 = obj as Territory;
			if(o2==null)
				return false;
			return object.Equals(_territoryid, o2._territoryid);
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "territoryid", Name = "employeeterritories_territoryid_fkey")]
		public EntityMSet<Employeeterritory> EmployeeTerritories
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Region> _Region;    
		
		[Association(Storage="_Region", ThisKey="regionid", Name="fk_terr_region")]
		[DebuggerNonUserCode]
		public Region Region {
			get { return this._Region.Entity; }
			set { this._Region.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "public.employeeterritories")]
	public partial class Employeeterritory : IModified
	{
		
		protected int _employeeid;
		protected string _territoryid;
	
		
		public Employeeterritory()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_employeeid", Name = "employeeid", DbType = "integer(32,0)", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public int EmployeeID
		{
		    get { return _employeeid; }
		    set { _employeeid = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_territoryid", Name = "territoryid", DbType = "character varying(20)", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public string TerritoryID
		{
		    get { return _territoryid; }
		    set { _territoryid = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _employeeid.GetHashCode() ^ (_territoryid == null ? 0 : _territoryid.GetHashCode());
		}
		public override bool Equals(object obj)
		{
			Employeeterritory o2 = obj as Employeeterritory;
			if(o2==null)
				return false;
			return _employeeid == o2._employeeid && object.Equals(_territoryid, o2._territoryid);
		}
		#endregion
	
		#region childtables
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Employee> _Employee;    
		
		[Association(Storage="_Employee", ThisKey="employeeid", Name="employeeterritories_employeeid_fkey")]
		[DebuggerNonUserCode]
		public Employee Employee {
			get { return this._Employee.Entity; }
			set { this._Employee.Entity = value; }
		}
		
		private System.Data.Linq.EntityRef<Territory> _Territory;    
		
		[Association(Storage="_Territory", ThisKey="territoryid", Name="employeeterritories_territoryid_fkey")]
		[DebuggerNonUserCode]
		public Territory Territory {
			get { return this._Territory.Entity; }
			set { this._Territory.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
}
