//#########################################################################
//generated by MysqlMetal on 2007-Oct-30 - extracted from file my_s.dbml.
//#########################################################################

using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Reflection;
using DBLinq.Linq;
using DBLinq.Linq.Mapping;

namespace Client2.user
{
    
	/// <summary>
	/// This class represents MySql database LinqTestDB.
	/// </summary>
	public partial class LinqTestDB : MContext
	{
		public LinqTestDB(string connStr):base(connStr)
		{
			Alltypes = new MTable<Alltype>(this);
			Customers = new MTable<Customer>(this);
			Employees = new MTable<Employee>(this);
			OrderDetails = new MTable<OrderDetail>(this);
			Orders = new MTable<Order>(this);
			Products = new MTable<Product>(this);
			Regions = new MTable<Region>(this);
			Shippers = new MTable<Shipper>(this);
			Territories = new MTable<Territorie>(this);
		}
	
		//these fields represent tables in database and are
		//ordered - parent tables first, child tables next. Do not change the order.
		public readonly MTable<Alltype> Alltypes;
		public readonly MTable<Customer> Customers;
		public readonly MTable<Employee> Employees;
		public readonly MTable<OrderDetail> OrderDetails;
		public readonly MTable<Order> Orders;
		public readonly MTable<Product> Products;
		public readonly MTable<Region> Regions;
		public readonly MTable<Shipper> Shippers;
		public readonly MTable<Territorie> Territories;
	
			
		[FunctionEx(Name = "getOrderCount", ProcedureOrFunction = "FUNCTION")]	
		public int getOrderCount([Parameter(Name = "custId", DbType = "INT UNSIGNED")] uint custId)	
		{	
			IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), custId);	
			return (int)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "hello0", ProcedureOrFunction = "FUNCTION")]	
		public string hello0()	
		{	
			IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));	
			return (string)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "hello1", ProcedureOrFunction = "FUNCTION")]	
		public string hello1([Parameter(Name = "s", DbType = "CHAR(20)")] string s)	
		{	
			IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s);	
			return (string)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "hello2", ProcedureOrFunction = "FUNCTION")]	
		public string hello2([Parameter(Name = "s", DbType = "CHAR(20)")] string s
				,[Parameter(Name = "s2", DbType = "int")] int s2)	
		{	
			IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s, s2);	
			return (string)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "sp_selOrders", ProcedureOrFunction = "PROCEDURE")]	
		public System.Data.DataSet sp_selOrders([Parameter(Name = "s", DbType = "CHAR(20)")] string s
				,[Parameter(Name = "s2", DbType = "int")]out  int s2)	
		{	
			IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s);	
				s2 = (int) result.GetParameterValue(1);	
			return result.ReturnValue as System.Data.DataSet;	
		}	
		
	
		
		[FunctionEx(Name = "sp_updOrders", ProcedureOrFunction = "PROCEDURE")]	
		public void sp_updOrders([Parameter(Name = "custID", DbType = "int")] int custID
				,[Parameter(Name = "prodId", DbType = "int")] int prodId)	
		{	
			IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), custID, prodId);	
			return ;	
		}	
		
	}
	
	
	
	[Table(Name = "alltypes")]
	public partial class Alltype : IModified
	{
		public bool IsModified { get; set; }
	
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected uint _int;
	
		protected uint? _intN;
	
		protected double _double;
	
		protected double _doubleN;
	
		protected decimal _decimal;
	
		protected decimal _decimalN;
	
		protected byte[] _blob;
	
		protected byte[] _blobN;
	
		protected bool _boolean;
	
		protected bool? _boolN;
	
		protected char _byte;
	
		protected char? _byteN;
	
		protected DateTime _DateTime;
	
		protected DateTime? _DateTimeN;
	
		protected float _float;
	
		protected float _floatN;
	
		protected string _char;
	
		protected string _charN;
	
		protected string _text;
	
		protected string _textN;
	
		protected short _short;
	
		protected short? _shortN;
	
		protected decimal _numeric;
	
		protected decimal _numericN;
	
		protected double _real;
	
		protected double _realN;
	
		protected short _smallInt;
	
		protected short? _smallIntN;
	
		protected DbLinq_EnumTest _DbLinq_EnumTest;
	
		
		#region costructors
		public Alltype()
		{
		}
		public Alltype(uint int_,uint? intN,double double_,double doubleN,decimal decimal_,decimal decimalN,byte[] blob,byte[] blobN,bool boolean,bool? boolN,char byte_,char? byteN,DateTime DateTime,DateTime? DateTimeN,float float_,float floatN,string char_,string charN,string text,string textN,short short_,short? shortN,decimal numeric,decimal numericN,double real,double realN,short smallInt,short? smallIntN,DbLinq_EnumTest DbLinq_EnumTest)
		{
		    this._int = int_;
		this._intN = intN;
		this._double = double_;
		this._doubleN = doubleN;
		this._decimal = decimal_;
		this._decimalN = decimalN;
		this._blob = blob;
		this._blobN = blobN;
		this._boolean = boolean;
		this._boolN = boolN;
		this._byte = byte_;
		this._byteN = byteN;
		this._DateTime = DateTime;
		this._DateTimeN = DateTimeN;
		this._float = float_;
		this._floatN = floatN;
		this._char = char_;
		this._charN = charN;
		this._text = text;
		this._textN = textN;
		this._short = short_;
		this._shortN = shortN;
		this._numeric = numeric;
		this._numericN = numericN;
		this._real = real;
		this._realN = realN;
		this._smallInt = smallInt;
		this._smallIntN = smallIntN;
		this._DbLinq_EnumTest = DbLinq_EnumTest;
		}
		#endregion
		
	
		#region properties - accessors
	
		[Column(Name = "int", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public uint int_
		{
		    get { return _int; }
		    set { _int = value; IsModified = true; }
		}
		
	
		[Column(Name = "intN", DbType = "int", CanBeNull = true)]
		[DebuggerNonUserCode]
		public uint? intN
		{
		    get { return _intN; }
		    set { _intN = value; IsModified = true; }
		}
		
	
		[Column(Name = "double", DbType = "double", CanBeNull = false)]
		[DebuggerNonUserCode]
		public double double_
		{
		    get { return _double; }
		    set { _double = value; IsModified = true; }
		}
		
	
		[Column(Name = "doubleN", DbType = "double", CanBeNull = true)]
		[DebuggerNonUserCode]
		public double doubleN
		{
		    get { return _doubleN; }
		    set { _doubleN = value; IsModified = true; }
		}
		
	
		[Column(Name = "decimal", DbType = "decimal", CanBeNull = false)]
		[DebuggerNonUserCode]
		public decimal decimal_
		{
		    get { return _decimal; }
		    set { _decimal = value; IsModified = true; }
		}
		
	
		[Column(Name = "decimalN", DbType = "decimal", CanBeNull = true)]
		[DebuggerNonUserCode]
		public decimal decimalN
		{
		    get { return _decimalN; }
		    set { _decimalN = value; IsModified = true; }
		}
		
	
		[Column(Name = "blob", DbType = "blob", CanBeNull = false)]
		[DebuggerNonUserCode]
		public byte[] blob
		{
		    get { return _blob; }
		    set { _blob = value; IsModified = true; }
		}
		
	
		[Column(Name = "blobN", DbType = "blob", CanBeNull = true)]
		[DebuggerNonUserCode]
		public byte[] blobN
		{
		    get { return _blobN; }
		    set { _blobN = value; IsModified = true; }
		}
		
	
		[Column(Name = "boolean", DbType = "tinyint", CanBeNull = false)]
		[DebuggerNonUserCode]
		public bool boolean
		{
		    get { return _boolean; }
		    set { _boolean = value; IsModified = true; }
		}
		
	
		[Column(Name = "boolN", DbType = "tinyint", CanBeNull = true)]
		[DebuggerNonUserCode]
		public bool? boolN
		{
		    get { return _boolN; }
		    set { _boolN = value; IsModified = true; }
		}
		
	
		[Column(Name = "byte", DbType = "tinyint", CanBeNull = false)]
		[DebuggerNonUserCode]
		public char byte_
		{
		    get { return _byte; }
		    set { _byte = value; IsModified = true; }
		}
		
	
		[Column(Name = "byteN", DbType = "tinyint", CanBeNull = true)]
		[DebuggerNonUserCode]
		public char? byteN
		{
		    get { return _byteN; }
		    set { _byteN = value; IsModified = true; }
		}
		
	
		[Column(Name = "DateTime", DbType = "datetime", CanBeNull = false)]
		[DebuggerNonUserCode]
		public DateTime DateTime
		{
		    get { return _DateTime; }
		    set { _DateTime = value; IsModified = true; }
		}
		
	
		[Column(Name = "DateTimeN", DbType = "datetime", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? DateTimeN
		{
		    get { return _DateTimeN; }
		    set { _DateTimeN = value; IsModified = true; }
		}
		
	
		[Column(Name = "float", DbType = "float", CanBeNull = false)]
		[DebuggerNonUserCode]
		public float float_
		{
		    get { return _float; }
		    set { _float = value; IsModified = true; }
		}
		
	
		[Column(Name = "floatN", DbType = "float", CanBeNull = true)]
		[DebuggerNonUserCode]
		public float floatN
		{
		    get { return _floatN; }
		    set { _floatN = value; IsModified = true; }
		}
		
	
		[Column(Name = "char", DbType = "char", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string char_
		{
		    get { return _char; }
		    set { _char = value; IsModified = true; }
		}
		
	
		[Column(Name = "charN", DbType = "char", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string charN
		{
		    get { return _charN; }
		    set { _charN = value; IsModified = true; }
		}
		
	
		[Column(Name = "text", DbType = "text", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string text
		{
		    get { return _text; }
		    set { _text = value; IsModified = true; }
		}
		
	
		[Column(Name = "textN", DbType = "text", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string textN
		{
		    get { return _textN; }
		    set { _textN = value; IsModified = true; }
		}
		
	
		[Column(Name = "short", DbType = "mediumint", CanBeNull = false)]
		[DebuggerNonUserCode]
		public short short_
		{
		    get { return _short; }
		    set { _short = value; IsModified = true; }
		}
		
	
		[Column(Name = "shortN", DbType = "mediumint", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? shortN
		{
		    get { return _shortN; }
		    set { _shortN = value; IsModified = true; }
		}
		
	
		[Column(Name = "numeric", DbType = "decimal", CanBeNull = false)]
		[DebuggerNonUserCode]
		public decimal numeric
		{
		    get { return _numeric; }
		    set { _numeric = value; IsModified = true; }
		}
		
	
		[Column(Name = "numericN", DbType = "decimal", CanBeNull = true)]
		[DebuggerNonUserCode]
		public decimal numericN
		{
		    get { return _numericN; }
		    set { _numericN = value; IsModified = true; }
		}
		
	
		[Column(Name = "real", DbType = "double", CanBeNull = false)]
		[DebuggerNonUserCode]
		public double real
		{
		    get { return _real; }
		    set { _real = value; IsModified = true; }
		}
		
	
		[Column(Name = "realN", DbType = "double", CanBeNull = true)]
		[DebuggerNonUserCode]
		public double realN
		{
		    get { return _realN; }
		    set { _realN = value; IsModified = true; }
		}
		
	
		[Column(Name = "smallInt", DbType = "smallint", CanBeNull = false)]
		[DebuggerNonUserCode]
		public short smallInt
		{
		    get { return _smallInt; }
		    set { _smallInt = value; IsModified = true; }
		}
		
	
		[Column(Name = "smallIntN", DbType = "smallint", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? smallIntN
		{
		    get { return _smallIntN; }
		    set { _smallIntN = value; IsModified = true; }
		}
		
	
		[Column(Name = "DbLinq_EnumTest", DbType = "smallint", CanBeNull = false)]
		[DebuggerNonUserCode]
		public DbLinq_EnumTest DbLinq_EnumTest
		{
		    get { return _DbLinq_EnumTest; }
		    set { _DbLinq_EnumTest = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column _int to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _int.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Alltype o2 = obj as Alltype;
			if(o2==null)
				return false;
			return _int.Equals(o2._int);
		}
		#endregion
	
		
		
	}
	
	
	
	[Table(Name = "customers")]
	public partial class Customer : IModified
	{
		public bool IsModified { get; set; }
	
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected uint _CustomerID;
	
		protected string _CompanyName;
	
		protected string _ContactName;
	
		protected string _ContactTitle;
	
		protected string _Address;
	
		protected string _City;
	
		protected string _Region;
	
		protected string _PostalCode;
	
		protected string _Country;
	
		protected string _Phone;
	
		protected string _Fax;
	
		
		#region costructors
		public Customer()
		{
		}
		public Customer(uint CustomerID,string CompanyName,string ContactName,string ContactTitle,string Address,string City,string Region,string PostalCode,string Country,string Phone,string Fax)
		{
		    this._CustomerID = CustomerID;
		this._CompanyName = CompanyName;
		this._ContactName = ContactName;
		this._ContactTitle = ContactTitle;
		this._Address = Address;
		this._City = City;
		this._Region = Region;
		this._PostalCode = PostalCode;
		this._Country = Country;
		this._Phone = Phone;
		this._Fax = Fax;
		}
		#endregion
		
	
		#region properties - accessors
	
		[Column(Name = "CustomerID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public uint CustomerID
		{
		    get { return _CustomerID; }
		    set { _CustomerID = value; IsModified = true; }
		}
		
	
		[Column(Name = "CompanyName", DbType = "varchar", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CompanyName
		{
		    get { return _CompanyName; }
		    set { _CompanyName = value; IsModified = true; }
		}
		
	
		[Column(Name = "ContactName", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ContactName
		{
		    get { return _ContactName; }
		    set { _ContactName = value; IsModified = true; }
		}
		
	
		[Column(Name = "ContactTitle", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ContactTitle
		{
		    get { return _ContactTitle; }
		    set { _ContactTitle = value; IsModified = true; }
		}
		
	
		[Column(Name = "Address", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Address
		{
		    get { return _Address; }
		    set { _Address = value; IsModified = true; }
		}
		
	
		[Column(Name = "City", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string City
		{
		    get { return _City; }
		    set { _City = value; IsModified = true; }
		}
		
	
		[Column(Name = "Region", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Region
		{
		    get { return _Region; }
		    set { _Region = value; IsModified = true; }
		}
		
	
		[Column(Name = "PostalCode", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string PostalCode
		{
		    get { return _PostalCode; }
		    set { _PostalCode = value; IsModified = true; }
		}
		
	
		[Column(Name = "Country", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Country
		{
		    get { return _Country; }
		    set { _Country = value; IsModified = true; }
		}
		
	
		[Column(Name = "Phone", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Phone
		{
		    get { return _Phone; }
		    set { _Phone = value; IsModified = true; }
		}
		
	
		[Column(Name = "Fax", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Fax
		{
		    get { return _Fax; }
		    set { _Fax = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column _CustomerID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _CustomerID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Customer o2 = obj as Customer;
			if(o2==null)
				return false;
			return _CustomerID.Equals(o2._CustomerID);
		}
		#endregion
	
		
		[Association(Storage = "null", OtherKey = "CustomerID", Name = "FK_orders_1")]
		public EntityMSet<Order> Orders
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		
	}
	
	
	
	[Table(Name = "employees")]
	public partial class Employee : IModified
	{
		public bool IsModified { get; set; }
	
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected uint _EmployeeID;
	
		protected string _LastName;
	
		protected string _FirstName;
	
		protected string _Title;
	
		protected DateTime? _HireDate;
	
		protected string _HomePhone;
	
		protected uint? _ReportsTo;
	
		
		#region costructors
		public Employee()
		{
		}
		public Employee(uint EmployeeID,string LastName,string FirstName,string Title,DateTime? HireDate,string HomePhone,uint? ReportsTo)
		{
		    this._EmployeeID = EmployeeID;
		this._LastName = LastName;
		this._FirstName = FirstName;
		this._Title = Title;
		this._HireDate = HireDate;
		this._HomePhone = HomePhone;
		this._ReportsTo = ReportsTo;
		}
		#endregion
		
	
		#region properties - accessors
	
		[Column(Name = "EmployeeID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public uint EmployeeID
		{
		    get { return _EmployeeID; }
		    set { _EmployeeID = value; IsModified = true; }
		}
		
	
		[Column(Name = "LastName", DbType = "varchar", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string LastName
		{
		    get { return _LastName; }
		    set { _LastName = value; IsModified = true; }
		}
		
	
		[Column(Name = "FirstName", DbType = "varchar", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string FirstName
		{
		    get { return _FirstName; }
		    set { _FirstName = value; IsModified = true; }
		}
		
	
		[Column(Name = "Title", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Title
		{
		    get { return _Title; }
		    set { _Title = value; IsModified = true; }
		}
		
	
		[Column(Name = "HireDate", DbType = "datetime", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? HireDate
		{
		    get { return _HireDate; }
		    set { _HireDate = value; IsModified = true; }
		}
		
	
		[Column(Name = "HomePhone", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string HomePhone
		{
		    get { return _HomePhone; }
		    set { _HomePhone = value; IsModified = true; }
		}
		
	
		[Column(Name = "ReportsTo", DbType = "int", CanBeNull = true)]
		[DebuggerNonUserCode]
		public uint? ReportsTo
		{
		    get { return _ReportsTo; }
		    set { _ReportsTo = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column _EmployeeID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _EmployeeID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Employee o2 = obj as Employee;
			if(o2==null)
				return false;
			return _EmployeeID.Equals(o2._EmployeeID);
		}
		#endregion
	
		
		[Association(Storage = "null", OtherKey = "EmployeeID", Name = "FK_Emp_ReportsToEmp")]
		public EntityMSet<Employee> Employees
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		
		private EntityRef<Employee> _Employee;    
		
		[Association(Storage="_Employee", ThisKey="ReportsTo", Name="FK_Emp_ReportsToEmp")]
		[DebuggerNonUserCode]
		public Employee ReportsToEmployee {
			get { return this._Employee.Entity; }
			set { this._Employee.Entity = value; }
		}
		
	}
	
	
	
	[Table(Name = "order details")]
	public partial class OrderDetail : IModified
	{
		public bool IsModified { get; set; }
	
		
		protected int _OrderID;
	
		protected int _ProductID;
	
		protected decimal _UnitPrice;
	
		protected short _Quantity;
	
		protected float _Discount;
	
		
		#region costructors
		public OrderDetail()
		{
		}
		public OrderDetail(int OrderID,int ProductID,decimal UnitPrice,short Quantity,float Discount)
		{
		    this._OrderID = OrderID;
		this._ProductID = ProductID;
		this._UnitPrice = UnitPrice;
		this._Quantity = Quantity;
		this._Discount = Discount;
		}
		#endregion
		
	
		#region properties - accessors
	
		[Column(Name = "OrderID", DbType = "int", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public int OrderID
		{
		    get { return _OrderID; }
		    set { _OrderID = value; IsModified = true; }
		}
		
	
		[Column(Name = "ProductID", DbType = "int", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public int ProductID
		{
		    get { return _ProductID; }
		    set { _ProductID = value; IsModified = true; }
		}
		
	
		[Column(Name = "UnitPrice", DbType = "decimal", CanBeNull = false)]
		[DebuggerNonUserCode]
		public decimal UnitPrice
		{
		    get { return _UnitPrice; }
		    set { _UnitPrice = value; IsModified = true; }
		}
		
	
		[Column(Name = "Quantity", DbType = "smallint", CanBeNull = false)]
		[DebuggerNonUserCode]
		public short Quantity
		{
		    get { return _Quantity; }
		    set { _Quantity = value; IsModified = true; }
		}
		
	
		[Column(Name = "Discount", DbType = "float", CanBeNull = false)]
		[DebuggerNonUserCode]
		public float Discount
		{
		    get { return _Discount; }
		    set { _Discount = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column _OrderID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _OrderID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			OrderDetail o2 = obj as OrderDetail;
			if(o2==null)
				return false;
			return _OrderID.Equals(o2._OrderID);
		}
		#endregion
	
		
		
	}
	
	
	
	[Table(Name = "orders")]
	public partial class Order : IModified
	{
		public bool IsModified { get; set; }
	
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected uint _OrderID;
	
		protected uint _CustomerID;
	
		protected uint _ProductID;
	
		protected DateTime _OrderDate;
	
		
		#region costructors
		public Order()
		{
		}
		public Order(uint OrderID,uint CustomerID,uint ProductID,DateTime OrderDate)
		{
		    this._OrderID = OrderID;
		this._CustomerID = CustomerID;
		this._ProductID = ProductID;
		this._OrderDate = OrderDate;
		}
		#endregion
		
	
		#region properties - accessors
	
		[Column(Name = "OrderID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public uint OrderID
		{
		    get { return _OrderID; }
		    set { _OrderID = value; IsModified = true; }
		}
		
	
		[Column(Name = "CustomerID", DbType = "int", CanBeNull = false)]
		[DebuggerNonUserCode]
		public uint CustomerID
		{
		    get { return _CustomerID; }
		    set { _CustomerID = value; IsModified = true; }
		}
		
	
		[Column(Name = "ProductID", DbType = "int", CanBeNull = false)]
		[DebuggerNonUserCode]
		public uint ProductID
		{
		    get { return _ProductID; }
		    set { _ProductID = value; IsModified = true; }
		}
		
	
		[Column(Name = "OrderDate", DbType = "datetime", CanBeNull = false)]
		[DebuggerNonUserCode]
		public DateTime OrderDate
		{
		    get { return _OrderDate; }
		    set { _OrderDate = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column _OrderID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _OrderID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Order o2 = obj as Order;
			if(o2==null)
				return false;
			return _OrderID.Equals(o2._OrderID);
		}
		#endregion
	
		
		
		private EntityRef<Customer> _Customer;    
		
		[Association(Storage="_Customer", ThisKey="CustomerID", Name="FK_orders_1")]
		[DebuggerNonUserCode]
		public Customer Customer {
			get { return this._Customer.Entity; }
			set { this._Customer.Entity = value; }
		}
		
		
		private EntityRef<Product> _Product;    
		
		[Association(Storage="_Product", ThisKey="ProductID", Name="FK_orders_prod")]
		[DebuggerNonUserCode]
		public Product Product {
			get { return this._Product.Entity; }
			set { this._Product.Entity = value; }
		}
		
	}
	
	
	
	[Table(Name = "products")]
	public partial class Product : IModified
	{
		public bool IsModified { get; set; }
	
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected uint _ProductID;
	
		protected string _ProductName;
	
		protected uint _SupplierID;
	
		protected uint _CategoryID;
	
		protected string _QuantityPerUnit;
	
		protected decimal _UnitPrice;
	
		protected short? _UnitsInStock;
	
		protected short? _UnitsOnOrder;
	
		protected short? _ReorderLevel;
	
		protected bool? _Discontinued;
	
		
		#region costructors
		public Product()
		{
		}
		public Product(uint ProductID,string ProductName,uint SupplierID,uint CategoryID,string QuantityPerUnit,decimal UnitPrice,short? UnitsInStock,short? UnitsOnOrder,short? ReorderLevel,bool? Discontinued)
		{
		    this._ProductID = ProductID;
		this._ProductName = ProductName;
		this._SupplierID = SupplierID;
		this._CategoryID = CategoryID;
		this._QuantityPerUnit = QuantityPerUnit;
		this._UnitPrice = UnitPrice;
		this._UnitsInStock = UnitsInStock;
		this._UnitsOnOrder = UnitsOnOrder;
		this._ReorderLevel = ReorderLevel;
		this._Discontinued = Discontinued;
		}
		#endregion
		
	
		#region properties - accessors
	
		[Column(Name = "ProductID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public uint ProductID
		{
		    get { return _ProductID; }
		    set { _ProductID = value; IsModified = true; }
		}
		
	
		[Column(Name = "ProductName", DbType = "varchar", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string ProductName
		{
		    get { return _ProductName; }
		    set { _ProductName = value; IsModified = true; }
		}
		
	
		[Column(Name = "SupplierID", DbType = "int", CanBeNull = false)]
		[DebuggerNonUserCode]
		public uint SupplierID
		{
		    get { return _SupplierID; }
		    set { _SupplierID = value; IsModified = true; }
		}
		
	
		[Column(Name = "CategoryID", DbType = "int", CanBeNull = false)]
		[DebuggerNonUserCode]
		public uint CategoryID
		{
		    get { return _CategoryID; }
		    set { _CategoryID = value; IsModified = true; }
		}
		
	
		[Column(Name = "QuantityPerUnit", DbType = "varchar", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string QuantityPerUnit
		{
		    get { return _QuantityPerUnit; }
		    set { _QuantityPerUnit = value; IsModified = true; }
		}
		
	
		[Column(Name = "UnitPrice", DbType = "decimal", CanBeNull = true)]
		[DebuggerNonUserCode]
		public decimal UnitPrice
		{
		    get { return _UnitPrice; }
		    set { _UnitPrice = value; IsModified = true; }
		}
		
	
		[Column(Name = "UnitsInStock", DbType = "smallint", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? UnitsInStock
		{
		    get { return _UnitsInStock; }
		    set { _UnitsInStock = value; IsModified = true; }
		}
		
	
		[Column(Name = "UnitsOnOrder", DbType = "smallint", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? UnitsOnOrder
		{
		    get { return _UnitsOnOrder; }
		    set { _UnitsOnOrder = value; IsModified = true; }
		}
		
	
		[Column(Name = "ReorderLevel", DbType = "smallint", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? ReorderLevel
		{
		    get { return _ReorderLevel; }
		    set { _ReorderLevel = value; IsModified = true; }
		}
		
	
		[Column(Name = "Discontinued", DbType = "bit", CanBeNull = true)]
		[DebuggerNonUserCode]
		public bool? Discontinued
		{
		    get { return _Discontinued; }
		    set { _Discontinued = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column _ProductID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _ProductID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Product o2 = obj as Product;
			if(o2==null)
				return false;
			return _ProductID.Equals(o2._ProductID);
		}
		#endregion
	
		
		[Association(Storage = "null", OtherKey = "ProductID", Name = "FK_orders_prod")]
		public EntityMSet<Order> Orders
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		
	}
	
	
	
	[Table(Name = "region")]
	public partial class Region : IModified
	{
		public bool IsModified { get; set; }
	
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected int _RegionID;
	
		protected string _RegionDescription;
	
		
		#region costructors
		public Region()
		{
		}
		public Region(int RegionID,string RegionDescription)
		{
		    this._RegionID = RegionID;
		this._RegionDescription = RegionDescription;
		}
		#endregion
		
	
		#region properties - accessors
	
		[Column(Name = "RegionID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public int RegionID
		{
		    get { return _RegionID; }
		    set { _RegionID = value; IsModified = true; }
		}
		
	
		[Column(Name = "RegionDescription", DbType = "varchar", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string RegionDescription
		{
		    get { return _RegionDescription; }
		    set { _RegionDescription = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column _RegionID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _RegionID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Region o2 = obj as Region;
			if(o2==null)
				return false;
			return _RegionID.Equals(o2._RegionID);
		}
		#endregion
	
		
		[Association(Storage = "null", OtherKey = "RegionID", Name = "FK_Terr_Region")]
		public EntityMSet<Territorie> Territories
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		
	}
	
	
	
	[Table(Name = "shippers")]
	public partial class Shipper : IModified
	{
		public bool IsModified { get; set; }
	
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected int _ShipperID;
	
		protected string _CompanyName;
	
		protected string _Phone;
	
		
		#region costructors
		public Shipper()
		{
		}
		public Shipper(int ShipperID,string CompanyName,string Phone)
		{
		    this._ShipperID = ShipperID;
		this._CompanyName = CompanyName;
		this._Phone = Phone;
		}
		#endregion
		
	
		#region properties - accessors
	
		[Column(Name = "ShipperID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public int ShipperID
		{
		    get { return _ShipperID; }
		    set { _ShipperID = value; IsModified = true; }
		}
		
	
		[Column(Name = "CompanyName", DbType = "varchar", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CompanyName
		{
		    get { return _CompanyName; }
		    set { _CompanyName = value; IsModified = true; }
		}
		
	
		[Column(Name = "Phone", DbType = "varchar", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Phone
		{
		    get { return _Phone; }
		    set { _Phone = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column _ShipperID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _ShipperID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Shipper o2 = obj as Shipper;
			if(o2==null)
				return false;
			return _ShipperID.Equals(o2._ShipperID);
		}
		#endregion
	
		
		
	}
	
	
	
	[Table(Name = "territories")]
	public partial class Territorie : IModified
	{
		public bool IsModified { get; set; }
	
		
		protected string _TerritoryID;
	
		protected string _TerritoryDescription;
	
		protected int _RegionID;
	
		
		#region costructors
		public Territorie()
		{
		}
		public Territorie(string TerritoryID,string TerritoryDescription,int RegionID)
		{
		    this._TerritoryID = TerritoryID;
		this._TerritoryDescription = TerritoryDescription;
		this._RegionID = RegionID;
		}
		#endregion
		
	
		#region properties - accessors
	
		[Column(Name = "TerritoryID", DbType = "varchar", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public string TerritoryID
		{
		    get { return _TerritoryID; }
		    set { _TerritoryID = value; IsModified = true; }
		}
		
	
		[Column(Name = "TerritoryDescription", DbType = "varchar", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string TerritoryDescription
		{
		    get { return _TerritoryDescription; }
		    set { _TerritoryDescription = value; IsModified = true; }
		}
		
	
		[Column(Name = "RegionID", DbType = "int", CanBeNull = false)]
		[DebuggerNonUserCode]
		public int RegionID
		{
		    get { return _RegionID; }
		    set { _RegionID = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column _TerritoryID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _TerritoryID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Territorie o2 = obj as Territorie;
			if(o2==null)
				return false;
			return _TerritoryID.Equals(o2._TerritoryID);
		}
		#endregion
	
		
		
		private EntityRef<Region> _Region;    
		
		[Association(Storage="_Region", ThisKey="RegionID", Name="FK_Terr_Region")]
		[DebuggerNonUserCode]
		public Region Region {
			get { return this._Region.Entity; }
			set { this._Region.Entity = value; }
		}
		
	}
	
}
