//#########################################################################
//generated by MysqlMetal on 2007-Sep-08 - extracted from server localhost.
//#########################################################################

using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using DBLinq.Linq;

namespace Client2.user
{
    
	/// <summary>
	/// This class represents PostgreSQL database LinqTestDB.
	/// </summary>
	public partial class LinqTestDB : MContext
	{
	    public LinqTestDB(string connStr):base(connStr)
	    {
	        Customers = new MTable<Customer>(this);
			Products = new MTable<Product>(this);
			Orders = new MTable<Order>(this);
			Alltypes = new MTable<Alltype>(this);
	    }
	
	    //these fields represent tables in database and are
	    //ordered - parent tables first, child tables next. Do not change the order.
	    public readonly MTable<Customer> Customers;
		public readonly MTable<Product> Products;
		public readonly MTable<Order> Orders;
		public readonly MTable<Alltype> Alltypes;
	}
	
	
	
	[Table(Name="customer")]
	public partial class Customer : IModified
	{
	    bool _isModified_;
	    public bool IsModified 
	    { 
	        get { return _isModified_; } 
	        set { _isModified_ = value; } 
	    }
	
	    [DBLinq.Linq.Mapping.AutoGenId] 
		protected int _customerid;
	
		protected string _companyname;
	
		protected string _contactname;
	
		protected string _city;
	
		protected string _postalcode;
	
		protected string _country;
	
		protected string _phone;
	
	    
		#region costructors
		public Customer()
		{
		}
		public Customer(int customerid,string companyname,string contactname,string city,string postalcode,string country,string phone)
		{
		    this._customerid = customerid;
		this._companyname = companyname;
		this._contactname = contactname;
		this._city = city;
		this._postalcode = postalcode;
		this._country = country;
		this._phone = phone;
		}
		#endregion
		
	
	    #region properties - accessors
	
		[Column(Name="customerid", IsDbGenerated=true, DbType="integer", IsPrimaryKey=true)]
		[DebuggerNonUserCode]
		public int CustomerID
		{
		    get { return _customerid; }
		    set { _customerid=value; _isModified_=true; }
		}
		
	
		[Column(Name="companyname", DbType="character varying")]
		[DebuggerNonUserCode]
		public string CompanyName
		{
		    get { return _companyname; }
		    set { _companyname=value; _isModified_=true; }
		}
		
	
		[Column(Name="contactname", DbType="character varying")]
		[DebuggerNonUserCode]
		public string ContactName
		{
		    get { return _contactname; }
		    set { _contactname=value; _isModified_=true; }
		}
		
	
		[Column(Name="city", DbType="character varying")]
		[DebuggerNonUserCode]
		public string City
		{
		    get { return _city; }
		    set { _city=value; _isModified_=true; }
		}
		
	
		[Column(Name="postalcode", DbType="character varying")]
		[DebuggerNonUserCode]
		public string PostalCode
		{
		    get { return _postalcode; }
		    set { _postalcode=value; _isModified_=true; }
		}
		
	
		[Column(Name="country", DbType="character varying")]
		[DebuggerNonUserCode]
		public string Country
		{
		    get { return _country; }
		    set { _country=value; _isModified_=true; }
		}
		
	
		[Column(Name="phone", DbType="character varying")]
		[DebuggerNonUserCode]
		public string Phone
		{
		    get { return _phone; }
		    set { _phone=value; _isModified_=true; }
		}
		
	#endregion
	    
	    #region GetHashCode(),Equals() - uses column _customerid to look up objects in liveObjectMap
	    //TODO: move this logic our of user code, into a generated class
	    public override int GetHashCode()
	    {
	        return _customerid.GetHashCode();
	    }
	    public override bool Equals(object obj)
	    {
	        Customer o2 = obj as Customer;
	        if(o2==null)
	            return false;
	        return _customerid.Equals(o2._customerid);
	    }
	    #endregion
	
	    
		[Association(Storage="null", OtherKey="customerid", Name="fk_order_customer")]
		public EntityMSet<Order> Orders
		{
		    get { return null; } //TODO L212
		}
	    
	}
	
	
	
	[Table(Name="products")]
	public partial class Product : IModified
	{
	    bool _isModified_;
	    public bool IsModified 
	    { 
	        get { return _isModified_; } 
	        set { _isModified_ = value; } 
	    }
	
	    [DBLinq.Linq.Mapping.AutoGenId] 
		protected int _productid;
	
		protected string _productname;
	
		protected int _supplierid;
	
		protected int _categoryid;
	
		protected string _quantityperunit;
	
	    
		#region costructors
		public Product()
		{
		}
		public Product(int productid,string productname,int supplierid,int categoryid,string quantityperunit)
		{
		    this._productid = productid;
		this._productname = productname;
		this._supplierid = supplierid;
		this._categoryid = categoryid;
		this._quantityperunit = quantityperunit;
		}
		#endregion
		
	
	    #region properties - accessors
	
		[Column(Name="productid", IsDbGenerated=true, DbType="integer", IsPrimaryKey=true)]
		[DebuggerNonUserCode]
		public int ProductID
		{
		    get { return _productid; }
		    set { _productid=value; _isModified_=true; }
		}
		
	
		[Column(Name="productname", DbType="character varying")]
		[DebuggerNonUserCode]
		public string ProductName
		{
		    get { return _productname; }
		    set { _productname=value; _isModified_=true; }
		}
		
	
		[Column(Name="supplierid", DbType="integer")]
		[DebuggerNonUserCode]
		public int SupplierID
		{
		    get { return _supplierid; }
		    set { _supplierid=value; _isModified_=true; }
		}
		
	
		[Column(Name="categoryid", DbType="integer")]
		[DebuggerNonUserCode]
		public int CategoryID
		{
		    get { return _categoryid; }
		    set { _categoryid=value; _isModified_=true; }
		}
		
	
		[Column(Name="quantityperunit", DbType="character varying")]
		[DebuggerNonUserCode]
		public string QuantityPerUnit
		{
		    get { return _quantityperunit; }
		    set { _quantityperunit=value; _isModified_=true; }
		}
		
	#endregion
	    
	    #region GetHashCode(),Equals() - uses column _productid to look up objects in liveObjectMap
	    //TODO: move this logic our of user code, into a generated class
	    public override int GetHashCode()
	    {
	        return _productid.GetHashCode();
	    }
	    public override bool Equals(object obj)
	    {
	        Product o2 = obj as Product;
	        if(o2==null)
	            return false;
	        return _productid.Equals(o2._productid);
	    }
	    #endregion
	
	    
		[Association(Storage="null", OtherKey="productid", Name="fk_order_product")]
		public EntityMSet<Order> Orders
		{
		    get { return null; } //TODO L212
		}
	    
	}
	
	
	
	[Table(Name="orders")]
	public partial class Order : IModified
	{
	    bool _isModified_;
	    public bool IsModified 
	    { 
	        get { return _isModified_; } 
	        set { _isModified_ = value; } 
	    }
	
	    [DBLinq.Linq.Mapping.AutoGenId] 
		protected int _orderid;
	
		protected int _customerid;
	
		protected int _productid;
	
		protected DateTime _orderdate;
	
	    
		#region costructors
		public Order()
		{
		}
		public Order(int orderid,int customerid,int productid,DateTime orderdate)
		{
		    this._orderid = orderid;
		this._customerid = customerid;
		this._productid = productid;
		this._orderdate = orderdate;
		}
		#endregion
		
	
	    #region properties - accessors
	
		[Column(Name="orderid", IsDbGenerated=true, DbType="integer", IsPrimaryKey=true)]
		[DebuggerNonUserCode]
		public int OrderID
		{
		    get { return _orderid; }
		    set { _orderid=value; _isModified_=true; }
		}
		
	
		[Column(Name="customerid", DbType="integer")]
		[DebuggerNonUserCode]
		public int CustomerID
		{
		    get { return _customerid; }
		    set { _customerid=value; _isModified_=true; }
		}
		
	
		[Column(Name="productid", DbType="integer")]
		[DebuggerNonUserCode]
		public int ProductID
		{
		    get { return _productid; }
		    set { _productid=value; _isModified_=true; }
		}
		
	
		[Column(Name="orderdate", DbType="timestamp without time zone")]
		[DebuggerNonUserCode]
		public DateTime OrderDate
		{
		    get { return _orderdate; }
		    set { _orderdate=value; _isModified_=true; }
		}
		
	#endregion
	    
	    #region GetHashCode(),Equals() - uses column _orderid to look up objects in liveObjectMap
	    //TODO: move this logic our of user code, into a generated class
	    public override int GetHashCode()
	    {
	        return _orderid.GetHashCode();
	    }
	    public override bool Equals(object obj)
	    {
	        Order o2 = obj as Order;
	        if(o2==null)
	            return false;
	        return _orderid.Equals(o2._orderid);
	    }
	    #endregion
	
	    
	    
		private EntityRef<Customer> _Customer;    
		
		[Association(Storage="_Customer", ThisKey="customerid", Name="fk_order_customer")]
		[DebuggerNonUserCode]
		public Customer Customer {
			get { return this._Customer.Entity; }
			set { this._Customer.Entity = value; }
		}
		
		
		private EntityRef<Product> _Product;    
		
		[Association(Storage="_Product", ThisKey="productid", Name="fk_order_product")]
		[DebuggerNonUserCode]
		public Product Product {
			get { return this._Product.Entity; }
			set { this._Product.Entity = value; }
		}
		
	}
	
	
	
	[Table(Name="alltypes")]
	public partial class Alltype : IModified
	{
	    bool _isModified_;
	    public bool IsModified 
	    { 
	        get { return _isModified_; } 
	        set { _isModified_ = value; } 
	    }
	
	    [DBLinq.Linq.Mapping.AutoGenId] 
		protected int _int;
	
		protected int? _intn;
	
		protected double _double;
	
		protected double _doublen;
	
		protected decimal _decimal;
	
		protected decimal _decimaln;
	
		protected DateTime _datetime;
	
		protected DateTime? _datetimen;
	
	    
		#region costructors
		public Alltype()
		{
		}
		public Alltype(int int_,int? intn,double double_,double doublen,decimal decimal_,decimal decimaln,DateTime datetime,DateTime? datetimen)
		{
		    this._int = int_;
		this._intn = intn;
		this._double = double_;
		this._doublen = doublen;
		this._decimal = decimal_;
		this._decimaln = decimaln;
		this._datetime = datetime;
		this._datetimen = datetimen;
		}
		#endregion
		
	
	    #region properties - accessors
	
		[Column(Name="int", IsDbGenerated=true, DbType="integer", IsPrimaryKey=true)]
		[DebuggerNonUserCode]
		public int Int
		{
		    get { return _int; }
		    set { _int=value; _isModified_=true; }
		}
		
	
		[Column(Name="intn", DbType="integer")]
		[DebuggerNonUserCode]
		public int? Intn
		{
		    get { return _intn; }
		    set { _intn=value; _isModified_=true; }
		}
		
	
		[Column(Name="double", DbType="double precision")]
		[DebuggerNonUserCode]
		public double Double
		{
		    get { return _double; }
		    set { _double=value; _isModified_=true; }
		}
		
	
		[Column(Name="doublen", DbType="double precision")]
		[DebuggerNonUserCode]
		public double Doublen
		{
		    get { return _doublen; }
		    set { _doublen=value; _isModified_=true; }
		}
		
	
		[Column(Name="decimal", DbType="numeric")]
		[DebuggerNonUserCode]
		public decimal Decimal
		{
		    get { return _decimal; }
		    set { _decimal=value; _isModified_=true; }
		}
		
	
		[Column(Name="decimaln", DbType="numeric")]
		[DebuggerNonUserCode]
		public decimal Decimaln
		{
		    get { return _decimaln; }
		    set { _decimaln=value; _isModified_=true; }
		}
		
	
		[Column(Name="datetime", DbType="timestamp without time zone")]
		[DebuggerNonUserCode]
		public DateTime Datetime
		{
		    get { return _datetime; }
		    set { _datetime=value; _isModified_=true; }
		}
		
	
		[Column(Name="datetimen", DbType="timestamp without time zone")]
		[DebuggerNonUserCode]
		public DateTime? Datetimen
		{
		    get { return _datetimen; }
		    set { _datetimen=value; _isModified_=true; }
		}
		
	#endregion
	    
	    #region GetHashCode(),Equals() - uses column _int to look up objects in liveObjectMap
	    //TODO: move this logic our of user code, into a generated class
	    public override int GetHashCode()
	    {
	        return _int.GetHashCode();
	    }
	    public override bool Equals(object obj)
	    {
	        Alltype o2 = obj as Alltype;
	        if(o2==null)
	            return false;
	        return _int.Equals(o2._int);
	    }
	    #endregion
	
	    
	    
	}
	
}
