#region MIT license
////////////////////////////////////////////////////////////////////
// MIT license:
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
// OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
//
// Authors:
//        Jiri George Moudry
////////////////////////////////////////////////////////////////////
#endregion

using System;
using System.Reflection;
using System.Collections.Generic;
using System.Text;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using DbLinq.Util;

namespace DbLinq.Util
{
    public class CSharp
    {
        /// <summary>
        /// Categorize type - this will determine further processing of retrieved types
        /// </summary>
        public static TypeEnum CategorizeType(Type t)
        {
            if(IsPrimitiveType(t))
                return TypeEnum.Primitive;
            if(AttribHelper.GetTableAttrib(t)!=null)
                return TypeEnum.Column;
            if (t.IsGenericType && t.GetGenericTypeDefinition()==typeof(Nullable<>))
            {
                //make 'double?' also primitive
                Type tInner = t.GetGenericArguments()[0];
                if (IsPrimitiveType(tInner))
                    return TypeEnum.Primitive;
            }
            return TypeEnum.Other;
        }

        /// <summary>
        /// if T is string or int or DateTime? or friends, return true.
        /// </summary>
        public static bool IsPrimitiveType(Type t)
        {
            if (t.IsGenericType)
            {
                Type genericType = t.GetGenericTypeDefinition();
                if (genericType == typeof(Nullable<>))
                {
                    Type[] genericArgs = t.GetGenericArguments();
                    bool ret = IsPrimitiveType(genericArgs[0]);
                    return ret;
                }
                else
                {
                    return false;
                }
            }

            #region IsBuiltinType
            bool isBuiltinType = t==typeof(string)
                || t==typeof(short)
                || t==typeof(ushort)
                || t==typeof(int)
                || t==typeof(uint)
                || t==typeof(long)
                || t==typeof(ulong)
                || t==typeof(float)
                || t==typeof(double)
                || t==typeof(decimal)
                || t==typeof(char)
                || t==typeof(byte)
                || t == typeof(bool)
                || t==typeof(DateTime); //DateTime: not strictly a primitive time
            return isBuiltinType;
            #endregion
        }

        /// <summary>
        /// a projection has only a default ctor and some fields.
        /// A projected class is generated by the compiler and has a name like $__proj4.
        /// 
        /// Update for Beta2: f__AnonymousType is also a proj, has one ctor, >0 params
        /// </summary>
        public static bool IsProjection(Type t)
        {
            ConstructorInfo[] cinfo = t.GetConstructors();
            if (cinfo.Length == 0 && t.IsValueType)
                return true; //allow projection into user-defined structs
            if(cinfo.Length<1)
                return false;
            if (t.Name.Contains("<>f__AnonymousType"))
                return true; //Beta2 logic
            //ParameterInfo[] ctor0_params = cinfo[0].GetParameters();
            //if (ctor0_params.Length != 0)
            //    return false;
            return true;
        }

        /// <summary>
        /// is this a type with a [Table] attribute?
        /// (Alternatively, you could check if it implements IModified)
        /// </summary>
        public static bool IsTableType(Type t)
        {
            TableAttribute tAttrib1 = AttribHelper.GetTableAttrib(t);
            return (tAttrib1!=null);
        }


        static readonly string[] Keywords = 
        {
           "int", "uint", "byte", "short", "ushort", "char"
            ,"decimal", "float", "double"
            ,"string", "DateTime"
            , "void", "object"

            ,"private", "protected", "public", "internal"
            ,"override", "virtual", "abstract", "partial", "static", "sealed", "readonly"
            ,"class", "struct", "namespace", "enum", "interface", "using", "const", "enum"

            ,"return", "if", "while", "for", "foreach"
            ,"yield", "break", "goto", "switch", "case", "default"

            , "as", "catch", "continue", "default", "delegate", "do"
            , "else", "false", "true", "fixed", "finally", "in", "is", "lock"
            , "new", "null", "out", "ref", "sizeof", "stackalloc", "throw", "typeof"
        };

        public static bool IsCsharpKeyword(string name)
        {
            //return Keywords.Contains(name); error CS0117: 'System.Array' does not contain a definition for 'Contains'???
            //return Keywords.Contains<string>(name);
            int index = System.Array.IndexOf<string>(Keywords, name);
            return index >= 0;
        }

        public static bool IsValueType(string csType)
        {
            switch (csType)
            {
            case "System.DateTime":
            case "System.Int64":
            case "System.Int16":
            case "System.Int32":
            case "System.Char":
            case "System.Byte":
            case "System.Double":
            case "System.Decimal":
            case "int":
            case "uint":
            case "char":
            case "byte":
            case "bool":
            case "long":
            case "short":
            case "ulong":
            case "ushort":
            case "decimal":
            case "double":
            case "float":
            case "DateTime":
                return true;
            default:
                return false;
            }
        }

        /// <summary>
        /// convert ('System.Int32',true) into 'int?'
        /// </summary>
        public static string FormatType(string csType, bool isNullable)
        {
            string csType2 = TypeNickName(csType);
            if (isNullable && IsValueType(csType))
                return csType2 + "?";
            return csType2;
        }

        /// <summary>
        /// given 'dbo.Order Details', return 'Order_Details'
        /// </summary>
        public static string FormatTableClassName(string sqlTableName)
        {
            if (sqlTableName.Contains("."))
            {
                int indx = sqlTableName.IndexOf(".");
                sqlTableName = sqlTableName.Substring(indx + 1);
            }
            sqlTableName = sqlTableName.Replace(" ", "_");
            return sqlTableName;
        }

        static string TypeNickName(string csType)
        {
            switch (csType)
            {
            case "System.String": return "string";
            case "System.Int64": return "long";
            case "System.Int16": return "short";
            case "System.Int32": return "int";
            case "System.Char": return "char";
            case "System.Byte": return "byte";
            case "System.Double": return "double";
            case "System.Decimal": return "decimal";
            case "System.Boolean": return "bool";
            case "System.Object": return "object";
            default: return csType;
            }
        }
    }
}
