////////////////////////////////////////////////////////////////////
//Initial author: Jiri George Moudry, 2006.
//License: LGPL. (Visit http://www.gnu.org)
//Commercial code may call into this library, if it's in a different module (DLL)
////////////////////////////////////////////////////////////////////

using System;
using System.Reflection;
using System.Collections.Generic;
using System.Text;
using System.Data.DLinq;

namespace DBLinq.util
{
    public class CSharp
    {
        /// <summary>
        /// Categorize type - this will determine further processing of retrieved types
        /// </summary>
        public static TypeEnum CategorizeType(Type t)
        {
            if(IsPrimitiveType(t))
                return TypeEnum.Primitive;
            if(AttribHelper.GetTableAttrib(t)!=null)
                return TypeEnum.Column;
            return TypeEnum.Other;
        }

        /// <summary>
        /// if T is string or int or friends, return true.
        /// </summary>
        public static bool IsPrimitiveType(Type t)
        {
            #region IsBuiltinType
            bool isBuiltinType = t==typeof(string)
                || t==typeof(short)
                || t==typeof(ushort)
                || t==typeof(int)
                || t==typeof(uint)
                || t==typeof(long)
                || t==typeof(ulong)
                || t==typeof(float)
                || t==typeof(double)
                || t==typeof(decimal)
                || t==typeof(char)
                || t==typeof(byte)
                || t==typeof(bool);
            return isBuiltinType;
            #endregion
        }

        /// <summary>
        /// a projection has only a default ctor and some fields.
        /// A projected class is generated by the compiler and has a name like $__proj4.
        /// </summary>
        public static bool IsProjection(Type t)
        {
            ConstructorInfo[] cinfo = t.GetConstructors();
            if(cinfo.Length!=1)
                return false;
            if(cinfo[0].GetParameters().Length!=0)
                return false;
            return true;
        }

        public static bool IsColumnType(Type t)
        {
            TableAttribute tAttrib1 = AttribHelper.GetTableAttrib(t);
            return (tAttrib1!=null);
        }


    }
}
