//#########################################################################
//generated by MySqlMetal on 2008-Jan-27 - extracted from server localhost.
//#########################################################################

using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Text;
using System.Linq;
//using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Reflection;
using DBLinq.Linq;
using DBLinq.Linq.Mapping;

namespace nwind
{
    
	/// <summary>
	/// This class represents MySql database Northwind.
	/// </summary>
	public partial class Northwind : DataContext
	{
		public Northwind(string connStr) : base(new MySql.Data.MySqlClient.MySqlConnection( connStr))
		{
		}
		public Northwind(System.Data.IDbConnection connection) : base(connection)
		{
		}
	
		//these fields represent tables in database and are
		//ordered - parent tables first, child tables next. Do not change the order.
		public Table<Region> Regions { get { return base.GetTable<Region>("Regions"); } }
		public Table<Supplier> Suppliers { get { return base.GetTable<Supplier>("Suppliers"); } }
		public Table<Shipper> Shippers { get { return base.GetTable<Shipper>("Shippers"); } }
		public Table<Category> Categories { get { return base.GetTable<Category>("Categories"); } }
		public Table<Customer> Customers { get { return base.GetTable<Customer>("Customers"); } }
		public Table<Employee> Employees { get { return base.GetTable<Employee>("Employees"); } }
		public Table<Territory> Territories { get { return base.GetTable<Territory>("Territories"); } }
		public Table<Employeeterritory> Employeeterritories { get { return base.GetTable<Employeeterritory>("Employeeterritories"); } }
		public Table<Order> Orders { get { return base.GetTable<Order>("Orders"); } }
		public Table<Product> Products { get { return base.GetTable<Product>("Products"); } }
		public Table<OrderDetail> OrderDetails { get { return base.GetTable<OrderDetail>("OrderDetails"); } }
	
		#region stored procs
	
		
		[FunctionEx(Name = "getOrderCount", ProcedureOrFunction = "FUNCTION")]	
		public int getOrderCount([Parameter(Name = "custId", DbType = "VARCHAR(5)")] string custId)	
		{	
			System.Data.Linq.IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), custId);	
			return (int)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "hello0", ProcedureOrFunction = "FUNCTION")]	
		public string hello0()	
		{	
			System.Data.Linq.IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));	
			return (string)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "hello1", ProcedureOrFunction = "FUNCTION")]	
		public string hello1([Parameter(Name = "s", DbType = "CHAR(20)")] string s)	
		{	
			System.Data.Linq.IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s);	
			return (string)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "hello2", ProcedureOrFunction = "FUNCTION")]	
		public string hello2([Parameter(Name = "s", DbType = "CHAR(20)")] string s
				,[Parameter(Name = "s2", DbType = "int")] int s2)	
		{	
			System.Data.Linq.IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s, s2);	
			return (string)result.ReturnValue;	
		}	
		
	
		
		[FunctionEx(Name = "sp_selOrders", ProcedureOrFunction = "PROCEDURE")]	
		public System.Data.DataSet sp_selOrders([Parameter(Name = "s", DbType = "CHAR(20)")] string s
				,[Parameter(Name = "s2", DbType = "int")]out  int s2)	
		{	
			System.Data.Linq.IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s);	
				s2 = (int) result.GetParameterValue(1);	
			return result.ReturnValue as System.Data.DataSet;	
		}	
		
	
		
		[FunctionEx(Name = "sp_updOrders", ProcedureOrFunction = "PROCEDURE")]	
		public void sp_updOrders([Parameter(Name = "custID", DbType = "int")] int custID
				,[Parameter(Name = "prodId", DbType = "int")] int prodId)	
		{	
			System.Data.Linq.IExecuteResult result = base.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), custID, prodId);	
			return ;	
		}	
		
	
	#endregion
	}
	
	
	
	[Table(Name = "region")]
	public partial class Region : IModified
	{
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected int _RegionID;
		protected string _RegionDescription;
	
		
		public Region()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_RegionID", Name = "RegionID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public int RegionID
		{
		    get { return _RegionID; }
		    set { _RegionID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_RegionDescription", Name = "RegionDescription", DbType = "varchar(50)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string RegionDescription
		{
		    get { return _RegionDescription; }
		    set { _RegionDescription = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _RegionID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Region o2 = obj as Region;
			if(o2==null)
				return false;
			return _RegionID == o2._RegionID;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "RegionID", Name = "territories_ibfk_1")]
		public EntityMSet<Territory> Territories
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "suppliers")]
	public partial class Supplier : IModified
	{
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected int _SupplierID;
		protected string _CompanyName;
		protected string _ContactName;
		protected string _ContactTitle;
		protected string _Address;
		protected string _City;
		protected string _Region;
		protected string _PostalCode;
		protected string _Country;
		protected string _Phone;
		protected string _Fax;
	
		
		public Supplier()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_SupplierID", Name = "SupplierID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public int SupplierID
		{
		    get { return _SupplierID; }
		    set { _SupplierID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_CompanyName", Name = "CompanyName", DbType = "varchar(40)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CompanyName
		{
		    get { return _CompanyName; }
		    set { _CompanyName = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ContactName", Name = "ContactName", DbType = "varchar(30)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ContactName
		{
		    get { return _ContactName; }
		    set { _ContactName = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ContactTitle", Name = "ContactTitle", DbType = "varchar(30)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ContactTitle
		{
		    get { return _ContactTitle; }
		    set { _ContactTitle = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Address", Name = "Address", DbType = "varchar(60)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Address
		{
		    get { return _Address; }
		    set { _Address = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_City", Name = "City", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string City
		{
		    get { return _City; }
		    set { _City = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Region", Name = "Region", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Region
		{
		    get { return _Region; }
		    set { _Region = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_PostalCode", Name = "PostalCode", DbType = "varchar(10)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string PostalCode
		{
		    get { return _PostalCode; }
		    set { _PostalCode = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Country", Name = "Country", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Country
		{
		    get { return _Country; }
		    set { _Country = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Phone", Name = "Phone", DbType = "varchar(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Phone
		{
		    get { return _Phone; }
		    set { _Phone = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Fax", Name = "Fax", DbType = "varchar(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Fax
		{
		    get { return _Fax; }
		    set { _Fax = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _SupplierID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Supplier o2 = obj as Supplier;
			if(o2==null)
				return false;
			return _SupplierID == o2._SupplierID;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "SupplierID", Name = "products_ibfk_2")]
		public EntityMSet<Product> Products
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "shippers")]
	public partial class Shipper : IModified
	{
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected int _ShipperID;
		protected string _CompanyName;
		protected string _Phone;
	
		
		public Shipper()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_ShipperID", Name = "ShipperID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public int ShipperID
		{
		    get { return _ShipperID; }
		    set { _ShipperID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_CompanyName", Name = "CompanyName", DbType = "varchar(40)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CompanyName
		{
		    get { return _CompanyName; }
		    set { _CompanyName = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Phone", Name = "Phone", DbType = "varchar(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Phone
		{
		    get { return _Phone; }
		    set { _Phone = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _ShipperID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Shipper o2 = obj as Shipper;
			if(o2==null)
				return false;
			return _ShipperID == o2._ShipperID;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "ShipperID", Name = "orders_ibfk_3")]
		public EntityMSet<Order> Orders
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "categories")]
	public partial class Category : IModified
	{
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected int _CategoryID;
		protected string _CategoryName;
		protected string _Description;
		protected byte[] _Picture;
	
		
		public Category()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_CategoryID", Name = "CategoryID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public int CategoryID
		{
		    get { return _CategoryID; }
		    set { _CategoryID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_CategoryName", Name = "CategoryName", DbType = "varchar(15)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CategoryName
		{
		    get { return _CategoryName; }
		    set { _CategoryName = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Description", Name = "Description", DbType = "text", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Description
		{
		    get { return _Description; }
		    set { _Description = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Picture", Name = "Picture", DbType = "blob", CanBeNull = true)]
		[DebuggerNonUserCode]
		public byte[] Picture
		{
		    get { return _Picture; }
		    set { _Picture = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _CategoryID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Category o2 = obj as Category;
			if(o2==null)
				return false;
			return _CategoryID == o2._CategoryID;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "CategoryID", Name = "products_ibfk_1")]
		public EntityMSet<Product> Products
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "customers")]
	public partial class Customer : IModified
	{
		
		protected string _CustomerID;
		protected string _CompanyName;
		protected string _ContactName;
		protected string _ContactTitle;
		protected string _Address;
		protected string _City;
		protected string _Region;
		protected string _PostalCode;
		protected string _Country;
		protected string _Phone;
		protected string _Fax;
	
		
		public Customer()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_CustomerID", Name = "CustomerID", DbType = "varchar(5)", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public string CustomerID
		{
		    get { return _CustomerID; }
		    set { _CustomerID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_CompanyName", Name = "CompanyName", DbType = "varchar(40)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string CompanyName
		{
		    get { return _CompanyName; }
		    set { _CompanyName = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ContactName", Name = "ContactName", DbType = "varchar(30)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ContactName
		{
		    get { return _ContactName; }
		    set { _ContactName = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ContactTitle", Name = "ContactTitle", DbType = "varchar(30)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ContactTitle
		{
		    get { return _ContactTitle; }
		    set { _ContactTitle = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Address", Name = "Address", DbType = "varchar(60)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Address
		{
		    get { return _Address; }
		    set { _Address = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_City", Name = "City", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string City
		{
		    get { return _City; }
		    set { _City = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Region", Name = "Region", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Region
		{
		    get { return _Region; }
		    set { _Region = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_PostalCode", Name = "PostalCode", DbType = "varchar(10)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string PostalCode
		{
		    get { return _PostalCode; }
		    set { _PostalCode = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Country", Name = "Country", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Country
		{
		    get { return _Country; }
		    set { _Country = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Phone", Name = "Phone", DbType = "varchar(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Phone
		{
		    get { return _Phone; }
		    set { _Phone = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Fax", Name = "Fax", DbType = "varchar(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Fax
		{
		    get { return _Fax; }
		    set { _Fax = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return (_CustomerID == null ? 0 : _CustomerID.GetHashCode());
		}
		public override bool Equals(object obj)
		{
			Customer o2 = obj as Customer;
			if(o2==null)
				return false;
			return object.Equals(_CustomerID, o2._CustomerID);
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "CustomerID", Name = "orders_ibfk_1")]
		public EntityMSet<Order> Orders
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "employees")]
	public partial class Employee : IModified
	{
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected int _EmployeeID;
		protected string _LastName;
		protected string _FirstName;
		protected string _Title;
		protected DateTime? _BirthDate;
		protected DateTime? _HireDate;
		protected string _Address;
		protected string _City;
		protected string _Region;
		protected string _PostalCode;
		protected string _Country;
		protected string _HomePhone;
		protected byte[] _Photo;
		protected string _Notes;
		protected int? _ReportsTo;
	
		
		public Employee()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_EmployeeID", Name = "EmployeeID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public int EmployeeID
		{
		    get { return _EmployeeID; }
		    set { _EmployeeID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_LastName", Name = "LastName", DbType = "varchar(20)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string LastName
		{
		    get { return _LastName; }
		    set { _LastName = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_FirstName", Name = "FirstName", DbType = "varchar(10)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string FirstName
		{
		    get { return _FirstName; }
		    set { _FirstName = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Title", Name = "Title", DbType = "varchar(30)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Title
		{
		    get { return _Title; }
		    set { _Title = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_BirthDate", Name = "BirthDate", DbType = "datetime", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? BirthDate
		{
		    get { return _BirthDate; }
		    set { _BirthDate = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_HireDate", Name = "HireDate", DbType = "datetime", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? HireDate
		{
		    get { return _HireDate; }
		    set { _HireDate = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Address", Name = "Address", DbType = "varchar(60)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Address
		{
		    get { return _Address; }
		    set { _Address = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_City", Name = "City", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string City
		{
		    get { return _City; }
		    set { _City = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Region", Name = "Region", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Region
		{
		    get { return _Region; }
		    set { _Region = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_PostalCode", Name = "PostalCode", DbType = "varchar(10)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string PostalCode
		{
		    get { return _PostalCode; }
		    set { _PostalCode = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Country", Name = "Country", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Country
		{
		    get { return _Country; }
		    set { _Country = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_HomePhone", Name = "HomePhone", DbType = "varchar(24)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string HomePhone
		{
		    get { return _HomePhone; }
		    set { _HomePhone = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Photo", Name = "Photo", DbType = "blob", CanBeNull = true)]
		[DebuggerNonUserCode]
		public byte[] Photo
		{
		    get { return _Photo; }
		    set { _Photo = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Notes", Name = "Notes", DbType = "text", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string Notes
		{
		    get { return _Notes; }
		    set { _Notes = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ReportsTo", Name = "ReportsTo", DbType = "int", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? ReportsTo
		{
		    get { return _ReportsTo; }
		    set { _ReportsTo = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _EmployeeID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Employee o2 = obj as Employee;
			if(o2==null)
				return false;
			return _EmployeeID == o2._EmployeeID;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "EmployeeID", Name = "employees_ibfk_1")]
		public EntityMSet<Employee> Employees
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		
		[Association(Storage = "null", OtherKey = "EmployeeID", Name = "employeeterritories_ibfk_1")]
		public EntityMSet<Employeeterritory> EmployeeTerritories
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		
		[Association(Storage = "null", OtherKey = "EmployeeID", Name = "orders_ibfk_2")]
		public EntityMSet<Order> Orders
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Employee> _ReportsToEmployee;    
		
		[Association(Storage="_ReportsToEmployee", ThisKey="ReportsTo", Name="employees_ibfk_1")]
		[DebuggerNonUserCode]
		public Employee ReportsToEmployee {
			get { return this._ReportsToEmployee.Entity; }
			set { this._ReportsToEmployee.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "territories")]
	public partial class Territory : IModified
	{
		
		protected string _TerritoryID;
		protected string _TerritoryDescription;
		protected int _RegionID;
	
		
		public Territory()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_TerritoryID", Name = "TerritoryID", DbType = "varchar(20)", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public string TerritoryID
		{
		    get { return _TerritoryID; }
		    set { _TerritoryID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_TerritoryDescription", Name = "TerritoryDescription", DbType = "varchar(50)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string TerritoryDescription
		{
		    get { return _TerritoryDescription; }
		    set { _TerritoryDescription = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_RegionID", Name = "RegionID", DbType = "int", CanBeNull = false)]
		[DebuggerNonUserCode]
		public int RegionID
		{
		    get { return _RegionID; }
		    set { _RegionID = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return (_TerritoryID == null ? 0 : _TerritoryID.GetHashCode());
		}
		public override bool Equals(object obj)
		{
			Territory o2 = obj as Territory;
			if(o2==null)
				return false;
			return object.Equals(_TerritoryID, o2._TerritoryID);
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "TerritoryID", Name = "employeeterritories_ibfk_2")]
		public EntityMSet<Employeeterritory> EmployeeTerritories
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Region> _Region;    
		
		[Association(Storage="_Region", ThisKey="RegionID", Name="territories_ibfk_1")]
		[DebuggerNonUserCode]
		public Region Region {
			get { return this._Region.Entity; }
			set { this._Region.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "employeeterritories")]
	public partial class Employeeterritory : IModified
	{
		
		protected int _EmployeeID;
		protected string _TerritoryID;
	
		
		public Employeeterritory()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_EmployeeID", Name = "EmployeeID", DbType = "int", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public int EmployeeID
		{
		    get { return _EmployeeID; }
		    set { _EmployeeID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_TerritoryID", Name = "TerritoryID", DbType = "varchar(20)", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public string TerritoryID
		{
		    get { return _TerritoryID; }
		    set { _TerritoryID = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _EmployeeID.GetHashCode() ^ (_TerritoryID == null ? 0 : _TerritoryID.GetHashCode());
		}
		public override bool Equals(object obj)
		{
			Employeeterritory o2 = obj as Employeeterritory;
			if(o2==null)
				return false;
			return _EmployeeID == o2._EmployeeID && object.Equals(_TerritoryID, o2._TerritoryID);
		}
		#endregion
	
		#region childtables
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Employee> _Employee;    
		
		[Association(Storage="_Employee", ThisKey="EmployeeID", Name="employeeterritories_ibfk_1")]
		[DebuggerNonUserCode]
		public Employee Employee {
			get { return this._Employee.Entity; }
			set { this._Employee.Entity = value; }
		}
		
		private System.Data.Linq.EntityRef<Territory> _Territory;    
		
		[Association(Storage="_Territory", ThisKey="TerritoryID", Name="employeeterritories_ibfk_2")]
		[DebuggerNonUserCode]
		public Territory Territory {
			get { return this._Territory.Entity; }
			set { this._Territory.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "orders")]
	public partial class Order : IModified
	{
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected int _OrderID;
		protected string _CustomerID;
		protected int? _EmployeeID;
		protected DateTime? _OrderDate;
		protected DateTime? _RequiredDate;
		protected DateTime? _ShippedDate;
		protected int? _ShipVia;
		protected decimal? _Freight;
		protected string _ShipName;
		protected string _ShipAddress;
		protected string _ShipCity;
		protected string _ShipRegion;
		protected string _ShipPostalCode;
		protected string _ShipCountry;
	
		
		public Order()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_OrderID", Name = "OrderID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public int OrderID
		{
		    get { return _OrderID; }
		    set { _OrderID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_CustomerID", Name = "CustomerID", DbType = "varchar(5)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string CustomerID
		{
		    get { return _CustomerID; }
		    set { _CustomerID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_EmployeeID", Name = "EmployeeID", DbType = "int", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? EmployeeID
		{
		    get { return _EmployeeID; }
		    set { _EmployeeID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_OrderDate", Name = "OrderDate", DbType = "datetime", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? OrderDate
		{
		    get { return _OrderDate; }
		    set { _OrderDate = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_RequiredDate", Name = "RequiredDate", DbType = "datetime", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? RequiredDate
		{
		    get { return _RequiredDate; }
		    set { _RequiredDate = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ShippedDate", Name = "ShippedDate", DbType = "datetime", CanBeNull = true)]
		[DebuggerNonUserCode]
		public DateTime? ShippedDate
		{
		    get { return _ShippedDate; }
		    set { _ShippedDate = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ShipVia", Name = "ShipVia", DbType = "int", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? ShipVia
		{
		    get { return _ShipVia; }
		    set { _ShipVia = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Freight", Name = "Freight", DbType = "decimal", CanBeNull = true)]
		[DebuggerNonUserCode]
		public decimal? Freight
		{
		    get { return _Freight; }
		    set { _Freight = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ShipName", Name = "ShipName", DbType = "varchar(40)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ShipName
		{
		    get { return _ShipName; }
		    set { _ShipName = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ShipAddress", Name = "ShipAddress", DbType = "varchar(60)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ShipAddress
		{
		    get { return _ShipAddress; }
		    set { _ShipAddress = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ShipCity", Name = "ShipCity", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ShipCity
		{
		    get { return _ShipCity; }
		    set { _ShipCity = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ShipRegion", Name = "ShipRegion", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ShipRegion
		{
		    get { return _ShipRegion; }
		    set { _ShipRegion = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ShipPostalCode", Name = "ShipPostalCode", DbType = "varchar(10)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ShipPostalCode
		{
		    get { return _ShipPostalCode; }
		    set { _ShipPostalCode = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ShipCountry", Name = "ShipCountry", DbType = "varchar(15)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string ShipCountry
		{
		    get { return _ShipCountry; }
		    set { _ShipCountry = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _OrderID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Order o2 = obj as Order;
			if(o2==null)
				return false;
			return _OrderID == o2._OrderID;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "OrderID", Name = "order details_ibfk_1")]
		public EntityMSet<OrderDetail> OrderDetails
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Customer> _Customer;    
		
		[Association(Storage="_Customer", ThisKey="CustomerID", Name="orders_ibfk_1")]
		[DebuggerNonUserCode]
		public Customer Customer {
			get { return this._Customer.Entity; }
			set { this._Customer.Entity = value; }
		}
		
		private System.Data.Linq.EntityRef<Employee> _Employee;    
		
		[Association(Storage="_Employee", ThisKey="EmployeeID", Name="orders_ibfk_2")]
		[DebuggerNonUserCode]
		public Employee Employee {
			get { return this._Employee.Entity; }
			set { this._Employee.Entity = value; }
		}
		
		private System.Data.Linq.EntityRef<Shipper> _Shipper;    
		
		[Association(Storage="_Shipper", ThisKey="ShipVia", Name="orders_ibfk_3")]
		[DebuggerNonUserCode]
		public Shipper Shipper {
			get { return this._Shipper.Entity; }
			set { this._Shipper.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "products")]
	public partial class Product : IModified
	{
		[DBLinq.Linq.Mapping.AutoGenId] 
		protected int _ProductID;
		protected string _ProductName;
		protected int? _SupplierID;
		protected int? _CategoryID;
		protected string _QuantityPerUnit;
		protected decimal? _UnitPrice;
		protected short? _UnitsInStock;
		protected short? _UnitsOnOrder;
		protected short? _ReorderLevel;
		protected bool _Discontinued;
	
		
		public Product()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_ProductID", Name = "ProductID", DbType = "int", IsPrimaryKey = true, IsDbGenerated = true)]
		[DebuggerNonUserCode]
		public int ProductID
		{
		    get { return _ProductID; }
		    set { _ProductID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ProductName", Name = "ProductName", DbType = "varchar(40)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public string ProductName
		{
		    get { return _ProductName; }
		    set { _ProductName = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_SupplierID", Name = "SupplierID", DbType = "int", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? SupplierID
		{
		    get { return _SupplierID; }
		    set { _SupplierID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_CategoryID", Name = "CategoryID", DbType = "int", CanBeNull = true)]
		[DebuggerNonUserCode]
		public int? CategoryID
		{
		    get { return _CategoryID; }
		    set { _CategoryID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_QuantityPerUnit", Name = "QuantityPerUnit", DbType = "varchar(20)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public string QuantityPerUnit
		{
		    get { return _QuantityPerUnit; }
		    set { _QuantityPerUnit = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_UnitPrice", Name = "UnitPrice", DbType = "decimal", CanBeNull = true)]
		[DebuggerNonUserCode]
		public decimal? UnitPrice
		{
		    get { return _UnitPrice; }
		    set { _UnitPrice = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_UnitsInStock", Name = "UnitsInStock", DbType = "smallint(6)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? UnitsInStock
		{
		    get { return _UnitsInStock; }
		    set { _UnitsInStock = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_UnitsOnOrder", Name = "UnitsOnOrder", DbType = "smallint(6)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? UnitsOnOrder
		{
		    get { return _UnitsOnOrder; }
		    set { _UnitsOnOrder = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ReorderLevel", Name = "ReorderLevel", DbType = "smallint(6)", CanBeNull = true)]
		[DebuggerNonUserCode]
		public short? ReorderLevel
		{
		    get { return _ReorderLevel; }
		    set { _ReorderLevel = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Discontinued", Name = "Discontinued", DbType = "bit(1)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public bool Discontinued
		{
		    get { return _Discontinued; }
		    set { _Discontinued = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _ProductID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			Product o2 = obj as Product;
			if(o2==null)
				return false;
			return _ProductID == o2._ProductID;
		}
		#endregion
	
		#region childtables
		
		[Association(Storage = "null", OtherKey = "ProductID", Name = "order details_ibfk_2")]
		public EntityMSet<OrderDetail> OrderDetails
		{
		    get { return null; } //L212 - child data available only when part of query
		}
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Category> _Category;    
		
		[Association(Storage="_Category", ThisKey="CategoryID", Name="products_ibfk_1")]
		[DebuggerNonUserCode]
		public Category Category {
			get { return this._Category.Entity; }
			set { this._Category.Entity = value; }
		}
		
		private System.Data.Linq.EntityRef<Supplier> _Supplier;    
		
		[Association(Storage="_Supplier", ThisKey="SupplierID", Name="products_ibfk_2")]
		[DebuggerNonUserCode]
		public Supplier Supplier {
			get { return this._Supplier.Entity; }
			set { this._Supplier.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
	
	
	[Table(Name = "order details")]
	public partial class OrderDetail : IModified
	{
		
		protected int _OrderID;
		protected int _ProductID;
		protected decimal _UnitPrice;
		protected short _Quantity;
		protected float _Discount;
	
		
		public OrderDetail()
		{
		}
		
	
		#region properties - accessors
	
		[Column(Storage = "_OrderID", Name = "OrderID", DbType = "int", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public int OrderID
		{
		    get { return _OrderID; }
		    set { _OrderID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_ProductID", Name = "ProductID", DbType = "int", IsPrimaryKey = true)]
		[DebuggerNonUserCode]
		public int ProductID
		{
		    get { return _ProductID; }
		    set { _ProductID = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_UnitPrice", Name = "UnitPrice", DbType = "decimal", CanBeNull = false)]
		[DebuggerNonUserCode]
		public decimal UnitPrice
		{
		    get { return _UnitPrice; }
		    set { _UnitPrice = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Quantity", Name = "Quantity", DbType = "smallint(6)", CanBeNull = false)]
		[DebuggerNonUserCode]
		public short Quantity
		{
		    get { return _Quantity; }
		    set { _Quantity = value; IsModified = true; }
		}
		
	
		[Column(Storage = "_Discount", Name = "Discount", DbType = "float", CanBeNull = false)]
		[DebuggerNonUserCode]
		public float Discount
		{
		    get { return _Discount; }
		    set { _Discount = value; IsModified = true; }
		}
		
	#endregion
		
		#region GetHashCode(),Equals() - uses column $fieldID to look up objects in liveObjectMap
		//TODO: move this logic our of user code, into a generated class
		public override int GetHashCode()
		{
			return _OrderID.GetHashCode() ^ _ProductID.GetHashCode();
		}
		public override bool Equals(object obj)
		{
			OrderDetail o2 = obj as OrderDetail;
			if(o2==null)
				return false;
			return _OrderID == o2._OrderID && _ProductID == o2._ProductID;
		}
		#endregion
	
		#region childtables
		#endregion
		#region parenttables
		
		private System.Data.Linq.EntityRef<Order> _Order;    
		
		[Association(Storage="_Order", ThisKey="OrderID", Name="order details_ibfk_1")]
		[DebuggerNonUserCode]
		public Order Order {
			get { return this._Order.Entity; }
			set { this._Order.Entity = value; }
		}
		
		private System.Data.Linq.EntityRef<Product> _Product;    
		
		[Association(Storage="_Product", ThisKey="ProductID", Name="order details_ibfk_2")]
		[DebuggerNonUserCode]
		public Product Product {
			get { return this._Product.Entity; }
			set { this._Product.Entity = value; }
		}
		#endregion
	
		public bool IsModified { get; set; }
	}
	
}
