USE [master]
GO
/****** Object:  Database [LinqTestDb]    Script Date: 12/06/2006 09:38:55 ******/
CREATE DATABASE [LinqTestDb] ON  PRIMARY 
( NAME = N'LinqTestDb')
 LOG ON 
( NAME = N'LinqTestDb_log')
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'LinqTestDb', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LinqTestDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LinqTestDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LinqTestDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LinqTestDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LinqTestDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LinqTestDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [LinqTestDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LinqTestDb] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [LinqTestDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LinqTestDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LinqTestDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LinqTestDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LinqTestDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LinqTestDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LinqTestDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LinqTestDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LinqTestDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [LinqTestDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LinqTestDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LinqTestDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LinqTestDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LinqTestDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LinqTestDb] SET  READ_WRITE 
GO
ALTER DATABASE [LinqTestDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LinqTestDb] SET  MULTI_USER 
GO
ALTER DATABASE [LinqTestDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LinqTestDb] SET DB_CHAINING OFF 

USE LinqTestDb
GO
CREATE TABLE Products
(
ProductID INT IDENTITY,
ProductName VARCHAR(33)
)
GO
